### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by davedavehong** [chemzqm/wept#10]
- 一打开就报了这个错。不知道啥意思，页面倒是能渲染

![image](https://cloud.githubusercontent.com/assets/10491999/19428825/dfdd3292-947e-11e6-8060-274206f5efe1.png)

- service.js 提供的系统debug的输出是强制开启的？我工程没开这个选项开始一直输出
- 进入子页面之后左上角会有一个返回按钮。然后我通过更改js文件里的data数据保存后是会自动重新加载页面刷新数据，但是没有左上角那个返回按钮了。
- 怎么关闭wept服务呢，看命令行只有-h, -V, -p这三个
- 当前登录用户的头像地址是强制用了你的微信头像吗
-切换端口命令是wept --port <3001> 提示语法不正确

我的demo地址：https://github.com/davedavehong/fenda-mock

**Comment by chemzqm** [comment]
> 一打开就报了这个错。不知道啥意思，页面倒是能渲染

这个我正在看

> 进入子页面之后左上角会有一个返回按钮。然后我通过更改js文件里的data数据保存后是会自动重新加载页面刷新数据，但是没有左上角那个返回按钮了。

你应该是修改的不是 pages 里面的 js 文件，这样刷新后前面页面就不存在，没办法返回，可以点右上 ... 然后点击刷新，下版本调整成刷新回主页好一点。因为非页面模板暂时是没办法热更新的。

> service.js 提供的系统debug的输出是强制开启的？我工程没开这个选项开始一直输出

这个是官方开发者就提供的，默认开启，需要 app.json 中设置 `debug:false` 关闭

> 怎么关闭wept服务呢，看命令行只有-h, -V, -p这三个

使用 ctrl-c 快捷键关闭

> 当前登录用户的头像地址是强制用了你的微信头像吗 -切换端口命令是wept --port <3001> 提示语法不正确

用户登录接口比较偷懒，没有使用微信 API（文档有注明），等有时间再看看换成真正的微信登录，
尖括号是占位符，使用 `wept --port 3001`

**Comment by davedavehong** [comment]
现在用官方开发小程序最大的痛点就是子页面每次有点小修改都要重启然后手动点进去（目前是先把子页面放在主页的tabBar下先调试好再放进去会方便一些），如果现在wept热启动后只能到主页的话，感觉会提升不了多大效率。刚试了下，在子页面点右上角的刷新，也是直接回首页了，相当于重启项目了。

app.json里的debug属性默认应该是false吧，我的工程中没写这个属性，在官方工具中就没输出degug信息了。

**Comment by chemzqm** [comment]
@davedavehong debug 我已改为默认 false，下个版本会更新。
如何刷新后回到当前页面待我研究一下，应该不是很困难。

感谢反馈。

**Comment by chemzqm** [comment]
@davedavehong 我这边刚修复了 http 请求的问题，运行你的小程序并没有发现报错。

**Comment by chemzqm** [comment]
@davedavehong 如果你修改的是页面 js wxml wxss 或者 json 文件的话， wept 会进行热更新，变化会实时展示到页面上，不会刷新页面的，只有你修改 app.json 或者 其它非页面的 js 时才会刷新。

**Comment by chemzqm** [comment]
@davedavehong 我看到了 `doAdblock`，所以强烈怀疑是因为你的 Adblock 导致页面出错了

**Comment by davedavehong** [comment]
@chemzqm 我的锅，sorry，确实是去广告插件的问题，导致那个报错。

刚刚更新到最新的wept 0.2.7，看了下热更新，发现wxml是可以的，不用刷新页面。但是page下的js文件的data中更新数据保存后会引起页面重新刷新，比如我那个工程的tabBar中「我的」，对应page的 mine，对mine.js中的data.myProfile.desc:"我的分币"，这个值改变后保存，页面就重新刷新了。不过js文件好像也不太需要热启动。wxss样式文件也是，改变后保存没什么反应，不过能够在chrome打开，就直接在上面调整样式好了，也不太需要热启动。page下的JSON文件也是，改一下导航栏标题也没反应。

难道跟我用windows有关系？

**Comment by davedavehong** [comment]
@chemzqm 我的锅，sorry，确实是去广告插件的问题，导致那个报错。

刚刚更新到最新的wept 0.2.7，看了下热更新，发现wxml是可以的，不用刷新页面。但是page下的js文件的data中更新数据保存后会引起页面重新刷新，比如我那个工程的tabBar中「我的」，对应page的 mine，对mine.js中的data.myProfile.desc:"我的分币"，这个值改变后保存，页面就重新刷新了。不过js文件好像也不太需要热启动。wxss样式文件也是，改变后保存没什么反应，不过能够在chrome打开，就直接在上面调整样式好了，也不太需要热启动。page下的JSON文件也是，改一下导航栏标题也没反应。

难道跟我用windows有关系？

**Comment by davedavehong** [comment]
@chemzqm 我的锅，sorry，确实是去广告插件的问题，导致那个报错。

刚刚更新到最新的wept 0.2.7，看了下热更新，发现wxml是可以的，不用刷新页面。但是page下的js文件的data中更新数据保存后会引起页面重新刷新，比如我那个工程的tabBar中「我的」，对应page的 mine，对mine.js中的data.myProfile.desc:"我的分币"，这个值改变后保存，页面就重新刷新了。不过js文件好像也不太需要热启动。wxss样式文件也是，改变后保存没什么反应，不过能够在chrome打开，就直接在上面调整样式好了，也不太需要热启动。page下的JSON文件也是，改一下导航栏标题也没反应。

难道跟我用windows有关系？

**Comment by chemzqm** [comment]
@davedavehong 你的 data 有个问题：
<img width="189" alt="screen shot 2016-10-18 at 12 56 29 pm" src="https://cloud.githubusercontent.com/assets/251450/19464870/57713642-9532-11e6-83b4-5538ec38e2b0.png">
`myProfile` 重复了，不过我这里是不用刷新页面而是热更新的
<img width="316" alt="screen shot 2016-10-18 at 12 57 29 pm" src="https://cloud.githubusercontent.com/assets/251450/19464884/7bcd5336-9532-11e6-847e-be2823a35be0.png">
下面 `Reload page: ` 表示热更新完成。
我这边 Mac 测试 wxss 和 json 的热更新也没问题，我到 windows 上看看。

**Comment by chemzqm** [comment]
@davedavehong 热更新 wxss 和 json 确实在 windows 上有问题，我修改 wxss 后台显示编译错误，修改 json 后台没有响应，是否可以把你修改 wxss 和 json 文件后的后台日志发给我看看？

**Comment by davedavehong** [comment]
@chemzqm 
录了一个[视频](elephstor.com/source/wept-win.mp4)，输出日志[见此](http://elephstor.com/source/test.txt)。

JS下：更新data数据会强制刷新页面
JSON下：保存后没反应，需要手动强刷页面
WXSS下：也是需要手动强刷

**Comment by chemzqm** [comment]
@davedavehong js 可能是文件路径判定有误，json 和 wxss 保存后没有响应我有点无法理解，很可能需要多花点时间去 debug

**Comment by chemzqm** [comment]
@davedavehong 我刚测试了 0.2.8 修复了路径问题以后我的 win7 可以正确热加载 json，wxss 和 javascript 文件了

**Comment by davedavehong** [comment]
@chemzqm 等下我看下，刚刚更新了一下没反应还是0.2.7。用npm卸载重装也是一样。

去看锤子发布会了。 - -

**Comment by chemzqm** [comment]
全局的模块需要执行 install 命令，我把更新方法写到文档里了

**Comment by chemzqm** [comment]
@davedavehong 3.0 版本添加了刷新后导航到当前页面的支持，可以使用测试版体验 https://github.com/chemzqm/wept/wiki/WEPT-0.3.0-beta-%E6%B5%8B%E8%AF%95%E7%89%88
