### ISSUE TITLE
centos7编译失败

### ISSUE THREAD

**Issue by jike-org** [chemzqm/wept#101]
* `wept --version`: 最新
* `node --version`: v6.10.1
* 操作系统: centos7
* 浏览器及浏览器版本: chrome
* 与官方工具表现不一致？

## 错误日志
编译失败

## 界面截图（可选）
<img width="549" alt="bug" src="https://cloud.githubusercontent.com/assets/26038762/26730811/b9c9ed88-47e4-11e7-9bcf-aa0bfa3a6f3f.png">

**Comment by chemzqm** [comment]
没有找到 wine，请参考文档：https://chemzqm.github.io/wept/#/home?id=%E5%AE%89%E8%A3%85-%E6%9B%B4%E6%96%B0
