### ISSUE TITLE
微信支付和登录API支持问题

### ISSUE THREAD

**Issue by ZAULCZ** [chemzqm/wept#103]
请问需要做微信支付和获取微信用户信息接口 需要怎么做呢？

**Comment by chemzqm** [comment]
wept 不支持微信服务端 API 调试，请通过官方工具调试，你可以通过判定 wept 环境：
```
const isWept = !!(__wxConfig && __wxConfig.directory)
```
判定 isWept 时跳过 API 请求。

**Comment by ZAULCZ** [comment]
您意思是在浏览器上这些API使用不了？可否有方法在浏览器上也能正常使用这些API呢

**Comment by chemzqm** [comment]
把微信的这些逻辑实现一下就是了，但是没有文档和源码的话，做起来太耗时

**Comment by ZAULCZ** [comment]
嗯，目前我看有几个API仅为模拟，并无真效。不知后续是否会完善呢

**Comment by chemzqm** [comment]
不会，没有那个时间和兴趣，个人觉得这块在官方工具里面调试就是了。

**Comment by ZAULCZ** [comment]
好的，O(∩_∩)O谢谢
