### ISSUE TITLE
eslint-plugin-node@5.1.1 requires a peer of eslint@>=3.1.0 but none was installed.

### ISSUE THREAD

**Issue by entrique** [chemzqm/wept#110]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 界面截图（可选）
![image](https://user-images.githubusercontent.com/4718721/30109606-8837490a-9339-11e7-964f-e17c4f9fad1e.png)

**Comment by YouthBaby** [comment]
这个你自己在全局 装一个eslint不就完了

**Comment by chemzqm** [comment]
@entrique 你需要设置命令行使用 utf8 编码
那个警告是你安足昂 eslint-plugin-node 导致的，跟 wept 没有关系
