### ISSUE TITLE
网络请求没有数据

### ISSUE THREAD

**Issue by Ivorfason** [chemzqm/wept#114]
在小程序中的wx.request的数据在转换完后的localhost:3000页面上无法显示，只有些占位符之类的...

**Comment by Ivorfason** [comment]
在chrome控制台看了下，好像是没有招待小程序的生命周期

**Comment by chemzqm** [comment]
看不明白，请描述的详细些

**Comment by Ivorfason** [comment]
![image](https://user-images.githubusercontent.com/15681593/31476494-3a8f56e4-aecc-11e7-8cdc-6a2e954e29ea.png)
就是在开启服务后，在浏览器里只能显示xml的内容，但是在onLoad（）方法里面的网络请求的数据没有加载出来

**Comment by Ivorfason** [comment]
![image](https://user-images.githubusercontent.com/15681593/31476527-627d9a08-aecc-11e7-902d-98b10f2ccb79.png)

**Comment by Ivorfason** [comment]
![1b112de5-7ace-4fee-ad51-a9edc57b4403](https://user-images.githubusercontent.com/15681593/31476590-b823cf0e-aecc-11e7-8f22-dd5d887e9f59.png)

**Comment by Ivorfason** [comment]
终端里面报这个错：
An error occured. { Error: spawn growlnotify ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs: 
   [ '--appIcon',
     'Safari',
     '-m',
     'Reloading pages/haivSharing/haivSharing.js',
     'liveload' ] }
