### ISSUE TITLE
footer 没有正确隐藏导致下面按钮无法点击

### ISSUE THREAD

**Issue by hangdui** [chemzqm/wept#12]
* `wept --version`: 0.2.6
* `node --version`: 6.2.0
* 操作系统: WIN10
* 浏览器及浏览器版本: chrome  53.0.2785.116 m
* 与官方工具表现不一致？
是的，不一致，用wept的时候，页面上出现的最后一个button的函数绑定总是失效，或者说感觉那个button就没有正确渲染。4个按钮的时候，第四个不能正常点击，3个按钮的时候就是第三个按钮无法点击。我去官方工具打开项目的时候是正常的。
刚才添加了tabBar之后，最后一个button就可以正常使用了。。。
## 错误日志
并没有报错。。

**Comment by chemzqm** [comment]
@hangdui 你在官方的 demo 可以重现这个 bug 吗？可以的话告诉我是哪个页面

**Comment by hangdui** [comment]
@chemzqm  其实我是昨天才发现你的功能，就去下了一个跑起来了，我用的是开发者工具第一次创建项目时候的quick start创建的demo然后加上官方手册上的测试用的button的demo，你说的官网demo是什么？https://mp.weixin.qq.com/debug/wxadoc/dev/demo.html 这个页面里的么？ 如果是的话，我现在就去重现一下

**Comment by chemzqm** [comment]
@hangdui 对，这里有所有页面组件和 API 的例子

**Comment by hangdui** [comment]
@chemzqm   这个上面的没有问题啊。。 要不然我把自己出问题的代码给你，你跑一下就知道了。。 我就是在index上写了几个按钮，每个按钮绑定一个方法。。。 但是最后一个就会失效

**Comment by hangdui** [comment]
@chemzqm   e  我刚才把chrome的mobile模式关了，按钮也恢复正常了，恢复Mobile模式，还是不能点击，有可能是浏览器的问题，我去更新一下试试

**Comment by chemzqm** [comment]
@hangdui 我的 Chrome 也偶尔出现移动事件无法响应的问题，此时重开 tab 就好了，但是不会像你说的上面按钮可以点，但是下面不行。你的  Chrome 跟我一样是最新版的，应该不用更新

**Comment by hangdui** [comment]
@chemzqm   e  更新了也不行。。 
![1](https://cloud.githubusercontent.com/assets/20531145/19466349/0072a2b2-953d-11e6-9436-23e039c1516c.png)
像图上的那个按钮，我遇到的情况就是点都点不动

**Comment by chemzqm** [comment]
@hangdui 你建个项目我去下载你源码看下吧，或者打个 zip 包传上来，我这边暂时重现不了

**Comment by hangdui** [comment]
[wx_test.zip](https://github.com/chemzqm/wept/files/535406/wx_test.zip)
@chemzqm   麻烦了。。

**Comment by chemzqm** [comment]
@hangdui 确定是我这里的 bug，我的 footer 没有正确隐藏掉，下版本会修复该 bug

**Comment by hangdui** [comment]
@chemzqm     好快。。  那我继续整了~
