### ISSUE TITLE
Uncaught TypeError: Cannot set property 'Promise' of undefined

### ISSUE THREAD

**Issue by hejinzhi** [chemzqm/wept#121]
* `wept --version`: 0.9.2 140900
* `node --version`: 7.10.1
* 操作系统: windows
* 浏览器及浏览器版本: chrome 63.0.3239.84
* 与官方工具表现不一致？

## 错误日志
Uncaught TypeError: Cannot set property 'Promise' of undefined

## 界面截图（可选）
![default](https://user-images.githubusercontent.com/18588816/34556961-82f9d5e6-f173-11e7-90b1-74500f04c96a.png)

**Comment by Ahren110** [comment]
同求

**Comment by DarrenHou1993** [comment]
这个工具作者不维护了吗。同求这个问题。 使用wepy编译后的项目。也出现这个问题

**Comment by cuijiemmx** [comment]
同求

**Comment by chemzqm** [comment]
0.9.2 可以直接使用 Promise 的，测试过了

**Comment by cuijiemmx** [comment]
@chemzqm 
wepy 1.7.1
wept 0.9.2
基础库 1.9.93
确实出这个错

**Comment by cuijiemmx** [comment]
@chemzqm 错误来自于wepy-async-function

**Comment by chemzqm** [comment]
@cuijiemmx 我把 window 以及其它变量屏蔽解除了。

**Comment by cuijiemmx** [comment]
@chemzqm 看到你发布了0.9.3，不过你应该没有把改动发布出去，刚升级了0.9.3的版本，还是老样子
![screen shot 2018-03-17 at 12 01 38 am](https://user-images.githubusercontent.com/3148003/37531312-c4c0ac58-2976-11e8-8ff3-777b7dc515df.png)
![screen shot 2018-03-17 at 12 02 37 am](https://user-images.githubusercontent.com/3148003/37531313-c4fc3f66-2976-11e8-85fb-52a5b4231fbb.png)

**Comment by cuijiemmx** [comment]
@chemzqm 我手动按你的方法改了下，从wepy-async-function中报的错误没有了，不过又有了个新的错误，来自于lodash的_freeGlobal.js，这个文件代码如下
```
/** Detect free variable `global` from Node.js. */
var freeGlobal = typeof global == 'object' && global && global.Object === Object && global;

module.exports = freeGlobal || this; //应该是因为this和freeGlobal都是undefined导致的

```
![screen shot 2018-03-17 at 12 13 09 am](https://user-images.githubusercontent.com/3148003/37531753-02c467fa-2978-11e8-81d3-8a1d8bd39bf1.png)

模拟器中是好的

**Comment by chemzqm** [comment]
@cuijiemmx 搞不清楚它在哪个版本加上了 global 变量，我也加上了。
wept 已经算废弃了，不建议使用。

**Comment by cuijiemmx** [comment]
@chemzqm 这么好的东西为啥要废弃啊，微信IDE太难调试了，DOM和CSS都隐藏了不少东西，有你这个简直就是调试神器啊，今天整了一下午的一个样式问题用wept 1分钟解决
或者你有什么办法能让我们happy debugging么？

**Comment by chemzqm** [comment]
@cuijiemmx 一种可行的办法是把 Elements 调试面板加到官方开发工具的 devtools 里面。
WEPT 的实现方式导致每次更新都要重新破解开发工具，开发组件功能，甚至许多调整组件工作，我目前是没有精力去投入了。

**Comment by cuijiemmx** [comment]
@chemzqm 把app.nw里全部的'--disable-devtools'去掉，然后在模拟器中UI上右键点一下出来个inspect，点它就出来了，多谢提示！
