### ISSUE TITLE
0.9.5没改好啊...

### ISSUE THREAD

**Issue by cuijiemmx** [chemzqm/wept#123]
@chemzqm 你加的global整出新问题了...
![screen shot 2018-03-17 at 1 14 22 am](https://user-images.githubusercontent.com/3148003/37535106-bc6d58b6-2981-11e8-8868-bf1d6f68ded3.png)

楼主再幸苦一下：）

**Comment by chemzqm** [comment]
@cuijiemmx 可能修复了

**Comment by cuijiemmx** [comment]
@chemzqm 貌似可以了，幸苦了
