### ISSUE TITLE
Linux 环境编译失败

### ISSUE THREAD

**Issue by Johnny-Li** [chemzqm/wept#13]
- `wept --version`: 0.2.7
- `node --version`: v6.6.0
- 操作系统: 
  Linux mint 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
- 浏览器及浏览器版本: Chrome Version: 51.0.2704.106
- 与官方工具表现不一致？
## 错误日志

会报 编译失败 的错误，详情请看截图
## 界面截图（可选）

![image](https://cloud.githubusercontent.com/assets/8186161/19468862/53ccf332-954b-11e6-87b9-92741411e282.png)

**Comment by chemzqm** [comment]
wcc 命令执行失败了，可以贴下后台命令行的日志吗？

**Comment by Johnny-Li** [comment]
@chemzqm Fyi.

listening on port 3000
  <-- GET /
  --> GET / 200 34ms 2.09kb
  <-- GET /css/index.css
  <-- GET /script/recorder.js
  <-- GET /script/build.js
  --> GET /css/index.css 200 17ms 2.94kb
  --> GET /script/recorder.js 200 15ms 1.48kb
  --> GET /script/build.js 200 28ms 73.99kb
  <-- GET /image/icon_component_HL.png
  <-- GET /image/icon_API.png
  --> GET /image/icon_component_HL.png 200 4ms 429b
  --> GET /image/icon_API.png 200 4ms 647b
  <-- GET /images/loading.gif
  --> GET /images/loading.gif 200 4ms 2.7kb
  <-- GET /appservice
  --> GET /appservice 200 49ms 2.19kb
  <-- GET /script/bridge.js
  <-- GET /script/service.js
  <-- GET /app/page/API/canvas/example.js
  <-- GET /app/page/API/get-location/format-location.js
  <-- GET /app/util/util.js
  <-- GET /app/app.js
  --> GET /script/bridge.js 200 18ms 6.97kb
  --> GET /script/service.js 200 17ms 16.93kb
  --> GET /app/page/API/canvas/example.js 200 18ms 6.71kb
  --> GET /app/util/util.js 200 16ms 547b
  --> GET /app/page/API/get-location/format-location.js 200 17ms 440b
  --> GET /app/app.js 200 15ms 388b
  <-- GET /app/page/component/index.js
  <-- GET /app/page/component/component-pages/action-sheet/action-sheet.js
  <-- GET /app/page/component/component-pages/audio/audio.js
  <-- GET /app/page/component/component-pages/button/button.js
  <-- GET /app/page/component/component-pages/canvas/canvas.js
  <-- GET /app/page/component/component-pages/checkbox/checkbox.js
  --> GET /app/page/component/index.js 200 13ms 1.51kb
  --> GET /app/page/component/component-pages/action-sheet/action-sheet.js 200 15ms 846b
  --> GET /app/page/component/component-pages/button/button.js 200 13ms 1.03kb
  --> GET /app/page/component/component-pages/audio/audio.js 200 16ms 739b
  --> GET /app/page/component/component-pages/canvas/canvas.js 200 17ms 1.28kb
  --> GET /app/page/component/component-pages/checkbox/checkbox.js 200 20ms 664b
  <-- GET /app/page/component/component-pages/form/form.js
  --> GET /app/page/component/component-pages/form/form.js 200 1ms 885b
  <-- GET /app/page/component/component-pages/icon/icon.js
  <-- GET /app/page/component/component-pages/image/image.js
  <-- GET /app/page/component/component-pages/input/input.js
  <-- GET /app/page/component/component-pages/map/map.js
  <-- GET /app/page/component/component-pages/modal/modal.js
  <-- GET /app/page/component/component-pages/navigator/navigator.js
  --> GET /app/page/component/component-pages/icon/icon.js 200 9ms 632b
  --> GET /app/page/component/component-pages/image/image.js 200 13ms 252b
  --> GET /app/page/component/component-pages/input/input.js 200 14ms 1.11kb
  --> GET /app/page/component/component-pages/map/map.js 200 16ms 764b
  --> GET /app/page/component/component-pages/modal/modal.js 200 18ms 649b
  --> GET /app/page/component/component-pages/navigator/navigator.js 200 19ms 266b
  <-- GET /app/page/component/component-pages/progress/progress.js
  <-- GET /app/page/component/component-pages/radio/radio.js
  <-- GET /app/page/component/component-pages/scroll-view/scroll-view.js
  <-- GET /app/page/component/component-pages/slider/slider.js
  <-- GET /app/page/component/component-pages/switch/switch.js
  <-- GET /app/page/component/component-pages/text/text.js
  --> GET /app/page/component/component-pages/progress/progress.js 200 13ms 263b
  --> GET /app/page/component/component-pages/switch/switch.js 200 5ms 485b
  --> GET /app/page/component/component-pages/radio/radio.js 200 10ms 646b
  --> GET /app/page/component/component-pages/slider/slider.js 200 7ms 495b
  --> GET /app/page/component/component-pages/scroll-view/scroll-view.js 200 8ms 930b
  <-- GET /app/page/component/component-pages/toast/toast.js
  --> GET /app/page/component/component-pages/text/text.js 200 6ms 689b
  <-- GET /app/page/component/component-pages/video/video.js
  <-- GET /app/page/component/component-pages/view/view.js
  --> GET /app/page/component/component-pages/toast/toast.js 200 7ms 709b
  <-- GET /app/page/component/component-pages/swiper/swiper.js
  --> GET /app/page/component/component-pages/video/video.js 200 7ms 543b
  --> GET /app/page/component/component-pages/view/view.js 200 5ms 247b
  <-- GET /app/page/component/component-pages/slide-tab/slide-tab.js
  <-- GET /app/page/component/component-pages/label/label.js
  <-- GET /app/page/component/component-pages/loading/loading.js
  <-- GET /app/page/component/component-pages/navigator/navigate.js
  <-- GET /app/page/component/component-pages/navigator/redirect.js
  --> GET /app/page/component/component-pages/swiper/swiper.js 200 9ms 925b
  --> GET /app/page/component/component-pages/slide-tab/slide-tab.js 200 11ms 794b
  --> GET /app/page/component/component-pages/label/label.js 200 10ms 1.64kb
  --> GET /app/page/component/component-pages/navigator/navigate.js 200 10ms 378b
  --> GET /app/page/component/component-pages/navigator/redirect.js 200 10ms 378b
  --> GET /app/page/component/component-pages/loading/loading.js 200 13ms 562b
  <-- GET /app/page/component/component-pages/picker/picker.js
  <-- GET /app/page/API/index/index.js
  <-- GET /app/page/API/login/login.js
  <-- GET /app/page/API/get-user-info/get-user-info.js
  <-- GET /app/page/API/request-payment/request-payment.js
  <-- GET /app/page/API/set-navigation-bar-title/set-navigation-bar-title.js
  --> GET /app/page/component/component-pages/picker/picker.js 200 6ms 727b
  --> GET /app/page/API/index/index.js 200 4ms 4.38kb
  --> GET /app/page/API/login/login.js 200 5ms 563b
  --> GET /app/page/API/request-payment/request-payment.js 200 3ms 248b
  --> GET /app/page/API/set-navigation-bar-title/set-navigation-bar-title.js 200 4ms 445b
  --> GET /app/page/API/get-user-info/get-user-info.js 200 5ms 832b
  <-- GET /app/page/API/navigation-bar-loading/navigation-bar-loading.js
  <-- GET /app/page/API/navigator/navigator.js
  <-- GET /app/page/API/pull-down-refresh/pull-down-refresh.js
  <-- GET /app/page/API/animation/animation.js
  <-- GET /app/page/API/get-network-type/get-network-type.js
  <-- GET /app/page/API/get-system-info/get-system-info.js
  --> GET /app/page/API/navigation-bar-loading/navigation-bar-loading.js 200 4ms 437b
  --> GET /app/page/API/navigator/navigator.js 200 4ms 430b
  --> GET /app/page/API/pull-down-refresh/pull-down-refresh.js 200 4ms 500b
  --> GET /app/page/API/animation/animation.js 200 3ms 2.14kb
  --> GET /app/page/API/get-network-type/get-network-type.js 200 3ms 692b
  --> GET /app/page/API/get-system-info/get-system-info.js 200 3ms 489b
  <-- GET /app/page/API/on-compass-change/on-compass-change.js
  --> GET /app/page/API/on-compass-change/on-compass-change.js 200 1ms 457b
  <-- GET /app/page/API/request/request.js
  <-- GET /app/page/API/web-socket/web-socket.js
  <-- GET /app/page/API/upload-file/upload-file.js
  <-- GET /app/page/API/download-file/download-file.js
  <-- GET /app/page/API/image/image.js
  <-- GET /app/page/API/voice/voice.js
  --> GET /app/page/API/request/request.js 200 7ms 215b
  --> GET /app/page/API/upload-file/upload-file.js 200 6ms 231b
  --> GET /app/page/API/web-socket/web-socket.js 200 9ms 227b
  --> GET /app/page/API/download-file/download-file.js 200 13ms 239b
  --> GET /app/page/API/image/image.js 200 14ms 1.39kb
  --> GET /app/page/API/voice/voice.js 200 13ms 2.28kb
  <-- GET /app/page/API/file/file.js
  <-- GET /app/page/API/on-accelerometer-change/on-accelerometer-change.js
  <-- GET /app/page/API/canvas/canvas.js
  --> GET /app/page/API/file/file.js 200 5ms 1.55kb
  <-- GET /app/page/API/background-audio/background-audio.js
  <-- GET /app/page/API/video/video.js
  <-- GET /app/page/API/get-location/get-location.js
  --> GET /app/page/API/canvas/canvas.js 200 10ms 918b
  --> GET /app/page/API/on-accelerometer-change/on-accelerometer-change.js 200 14ms 2.14kb
  <-- GET /app/page/API/open-location/open-location.js
  --> GET /app/page/API/background-audio/background-audio.js 200 12ms 2.57kb
  --> GET /app/page/API/video/video.js 200 12ms 1.31kb
  --> GET /app/page/API/get-location/get-location.js 200 11ms 681b
  --> GET /app/page/API/open-location/open-location.js 200 5ms 512b
  <-- GET /app/page/API/storage/storage.js
  --> GET /app/page/API/storage/storage.js 200 3ms 1.86kb
  <-- GET /app/page/component/index.wxml
Error: Command failed: /usr/local/node/lib/node_modules/.wept_npminstall/node_modules/.0.2.7@wept/bin/wcc -d ./page/component/index.wxml
/usr/local/node/lib/node_modules/.wept_npminstall/node_modules/.0.2.7@wept/bin/wcc: 1: /usr/local/node/lib/node_modules/.wept_npminstall/node_modules/.0.2.7@wept/bin/wcc: Syntax error: "(" unexpected

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: page/component/index.wxml 编译失败，请检查
    at /usr/local/node/lib/node_modules/.wept_npminstall/node_modules/.0.2.7@wept/lib/parser.js:46:27
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Error: page/component/index.wxml 编译失败，请检查
    at /usr/local/node/lib/node_modules/.wept_npminstall/node_modules/.0.2.7@wept/lib/parser.js:46:27
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  --> GET /app/page/component/index.wxml 404 39ms -

**Comment by chemzqm** [comment]
看来官方开发者工具提供 wcc 命令 linux 下无法使用，这个暂时解决不了... 😭

**Comment by Johnny-Li** [comment]
@chemzqm 好的，没关系

**Comment by chemzqm** [comment]
0.6.6 版本已支持通过 wine 在 linux 环境下编译 wxss 和 wxml 文件。

**Comment by leinue** [comment]
ubuntu编译wxss文件失败

ERR: ./style/base/fn.wxss(2:1): unexpected token `@import`
./style/base/mixin/setArrow.wxss(11:15): unexpected `(` at pos 338
./style/base/mixin/setOnepx.wxss(1:13): unexpected token `(`
./style/base/mixin/text.wxss(1:11): unexpected token `(`
./style/base/variable/color.wxss(2:20): unexpected token `#1AAD19`
./style/base/variable/global.wxss(2:32): unexpected token `"Helvetica Neue"`
./style/base/variable/weui-button.wxss(1:20): unexpected token `15px`
./style/base/variable/weui-cell.wxss(13:90): unexpected `�` at pos 404
./style/base/variable/weui-dialog.wxss(1:29): unexpected token `#FFFFFF`
./style/base/variable/weui-grid.wxss(1:22): unexpected token `#D9D9D9`
./style/base/variable/weui-msg.wxss(1:20): unexpected token `36px`
./style/base/variable/weui-progress.wxss(1:18): unexpected token `#EBEBEB`
./style/widget/weui-button/weui-button.wxss(5:5): unexpected `&` at pos 83
./style/widget/weui-cell/weui-access.wxss(9:5): unexpected `&` at pos 154
./style/widget/weui-cell/weui-cell.wxss(8:41): unexpected `�` at pos 220
./style/widget/weui-cell/weui-check.wxss(15:5): unexpected `&` at pos 242
./style/widget/weui-cell/weui-form/weui-form-preview.wxss(6:5): unexpected `&` at pos 114
./style/widget/weui-cell/weui-form/weui-form_common.wxss(9:15): unexpected `(` at pos 156
./style/widget/weui-cell/weui-form/weui-select.wxss(17:5): unexpected `&` at pos 330
./style/widget/weui-cell/weui-form/weui-vcode.wxss(22:5): unexpected `&` at pos 598
./style/widget/weui-cell/weui-uploader.wxss(32:5): unexpected `&` at pos 702
./style/widget/weui-footer/weui-footer.wxss(24:5): unexpected `&` at pos 438
./style/widget/weui-grid/weui-grid.wxss(17:5): unexpected `&` at pos 423
./style/widget/weui-media-box/weui-media-box.wxss(6:5): unexpected `&` at pos 97
./style/widget/weui-panel/weui-panel.wxss(7:5): unexpected `&` at pos 104
./style/widget/weui-searchbar/weui-searchbar.wxss(3:23): unexpected token `28px`
./style/widget/weui-tab/weui-navbar.wxss(21:5): unexpected `&` at pos 352
./style/widget/weui-tips/weui-loadmore.wxss(32:5): unexpected `&` at pos 615
