### ISSUE TITLE
使用 babel 编译 es6 代码

### ISSUE THREAD

**Issue by chemzqm** [chemzqm/wept#16]
与官方工具保持一致

**Comment by blackcater** [comment]
希望可以加上 less, sass的支持 以及 ES6支持

**Comment by chemzqm** [comment]
es6 是官方支持的，我这里如果加上 less 和 sass 支持会导致项目无法在官方工具以及线上正常使用的，如果官方支持 less 或者 sass，我这边会尽快跟进。

**Comment by chemzqm** [comment]
eda10dc
