### ISSUE TITLE
建议添加自定义项目目录的命令行参数

### ISSUE THREAD

**Issue by f111fei** [chemzqm/wept#19]
目前是使用`process.cwd()`作为项目目录， 某些情况下可能不太灵活，希望添加自定义项目目录的设置参数

**Comment by chemzqm** [comment]
我感觉那样可能不太适合，因为有不少地方依赖相对路径的解析。

**Comment by chemzqm** [comment]
已添加，下个版本会上

**Comment by f111fei** [comment]
Nice!!!
