### ISSUE TITLE
使用报错：TypeError: logs.unshift is not a function

### ISSUE THREAD

**Issue by huike1989** [chemzqm/wept#2]
log 存储在localstorage。 在 app.js  中
刷新页面的时候
var logs = wx.getStorageSync('logs') || [];会报错

是不是需要JSON.parse  下呢？

**Comment by chemzqm** [comment]
@huike1989 确实是个 bug，我正在排查中

**Comment by chemzqm** [comment]
@huike1989 已修复，需要你手工清除下浏览器 localStorage 缓存确保数据没问题。

**Comment by moxiaobei2** [comment]
已经更新了吗？还是报错的？
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at fs.readFile.e (C:\Users\bb\AppData\Roaming\npm\node_modules\wept\lib\util.js:29:34)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

**Comment by chemzqm** [comment]
@moxiaobei2 你这个报错应该是你的 json 文件格式错了，导致文件无法解析

**Comment by chemzqm** [comment]
新版提供了数据缓存清理操作

![one](https://cloud.githubusercontent.com/assets/251450/19409213/e6642734-9301-11e6-8865-33363d66a4d7.jpeg)

点击右上角 ... 唤出这个菜单，如果数据有问题，可以点击`清理数据缓存重置一下`
