### ISSUE TITLE
希望添加使用脚本的启动方式

### ISSUE THREAD

**Issue by f111fei** [chemzqm/wept#22]
目前只能通过命令行启动wept。  希望给一个入口能够通过js脚本使用wept模块。

如:

```
var wept = require('wept');
var root = 'xxx' //项目目录
wept(root, {
  port: 3000
});
```

按照 #19 的解决方案似乎要支持自定义项目根目录，使用 `process.chdir` 不是一个很好的办法。如果能重构代码将项目目录储存起来，在使用fs操作相对路径的文件时加上项目目录前缀应该比较靠谱。

我大致看了下代码，如果要这样做，需要改的地方有些多，如果你觉得这样做是必要的，我明天可以帮忙重构一下。

**Comment by chemzqm** [comment]
我把 package.json 的 main 改到 `build/server.js` 就可以支持 require 了，不用改代码。

**Comment by f111fei** [comment]
这样不行的， server.js 没有设置项目根目录， process.cwd() 不一定是项目目录。而且如果使用脚本的方式调用，修改全局的 `process.chdir` 是非常危险的操作，会影响其他模块

**Comment by chemzqm** [comment]
@f111fei 那你来提个 PR 吧

**Comment by f111fei** [comment]
@chemzqm 好的，我明天研究看看

**Comment by chemzqm** [comment]
@f111fei 我建议你用 `child_process.spawn` 新开进程运行 wept，这个接口可以指定 cwd，没必要给代码增加太多复杂度。
