### ISSUE TITLE
图片显示不了

### ISSUE THREAD

**Issue by jkgeekJack** [chemzqm/wept#23]
* `wept --version`: 0.29
* `node --version`: 4.4.4
* 操作系统: win10
* 浏览器及浏览器版本chrome: 

## 错误日志
图片显示不了
774a098cbcce19ee60760680dc9f5604_is.jpg:1 GET http://pic3.zhimg.com/774a098cbcce19ee60760680dc9f5604_is.jpg 403 (Forbidden)

**Comment by jkgeekJack** [comment]
原来你这个不支持http。。。。，只能全部改成https，能不能改一下兼容http的图片啊

**Comment by chemzqm** [comment]
我这里可以正常显示的，应该是图片服务器的问题或者网络防火墙的问题，不是前端的问题。

**Comment by chemzqm** [comment]
@jkgeekJack 你用的是哪个接口？

**Comment by jkgeekJack** [comment]
知乎日报api

**Comment by chemzqm** [comment]
@jkgeekJack 我这边可以正常使用知乎日报 API 的，可能就是网络问题。
![1](https://cloud.githubusercontent.com/assets/251450/19550598/c832dac4-96dc-11e6-9eef-d88d44d0e934.jpeg)

**Comment by jkgeekJack** [comment]
你是用你自家的wept还是官方的，我用官方的就可以，浏览器上就不行

**Comment by chemzqm** [comment]
![1](https://cloud.githubusercontent.com/assets/251450/19557203/43e43bd0-96f7-11e6-95d4-685204af5100.jpeg)
可能是你浏览器插件问题？用 devtools 检查下请求和响应。
