### ISSUE TITLE
希望添加命令行参数设置mac下不自动打开浏览器

### ISSUE THREAD

**Issue by f111fei** [chemzqm/wept#25]
目前默认情况mac下会自动打开浏览器窗口

**Comment by chemzqm** [comment]
正在考虑加个参数

**Comment by f111fei** [comment]
:+1:  Cool!!!  不过好像这样实现，默认就不会打开了，和之前的行为不一样 :worried: 。 你如果觉得ok就这样吧，反正我不用mac， 哈哈

**Comment by chemzqm** [comment]
小功能，影响不大
