### ISSUE TITLE
No external template usable

### ISSUE THREAD

**Issue by morphet81** [chemzqm/wept#26]
* `wept --version`: 0.2.9
* `node --version`: 5.7.0
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 界面截图（可选）

Impossible to import template file. It's working in WeChat IDE.

**Comment by chemzqm** [comment]
@morphet81 请说明你的操作系统，最好把你写的 import 和 template 文件也发给我，因为这块我测试过 Mac 和 win7 是可用的

**Comment by morphet81** [comment]
Hi,

I'm on Mac. Here are screenshots of the project structure and import line. The console said couldn't find the imported file.

Le 20/10/2016 à 15:48, Qiming zhao a écrit :

@morphet81<https://github.com/morphet81> 请说明你的操作系统，最好把你写的 import 和 template 文件也发给我，因为这块我测试过 Mac 和 win7 是可用的

**Comment by chemzqm** [comment]
@morphet81 我在 github 上看不到你发的附件，我需要你写 import 那部分的代码

**Comment by morphet81** [comment]
Yeah I see it.... Here is the code
``` html
<import src="/templates/message.wxml" />

<view class="container">
    <input type="text" bindinput="editMessage" value="{{newMessage}}" placeholder="Type message here" />
    <button bindtap="addMessage">Add</button>
    <block wx:for="{{messages}}" wx:for-item="message">
        <template is="message" data="{{message:message}}" />
    </block>
</view>
```

Pages are in "/pages/message/"

**Comment by chemzqm** [comment]
@morphet81 是我这里的 bug，当时解析时没有对 ’/‘ 开头的全路径做好兼容。

**Comment by morphet81** [comment]
Ok thanks. Changing to '../../' now works. It was not working earlier that day, I think there are some bugs in WeChat IDE with the location of templates.

**Comment by morphet81** [comment]
Pretty nice tool though ! 很谢谢你！

**Comment by chemzqm** [comment]
@morphet81 也感谢你的反馈，等下版本发布就可以使用绝对路径的 template 了
