### ISSUE TITLE
不支持import

### ISSUE THREAD

**Issue by Poordeveloper** [chemzqm/wept#27]
* `wept --version`: 最新
* `node --version`: v6.8.1
* 操作系统: mac
* 浏览器及浏览器版本: chrome  53.0.2785.143 (64-bit)
* 与官方工具表现不一致？

## 错误日志

import Parse from '../libs/parse';

Uncaught SyntaxError: Unexpected token import

**Comment by chemzqm** [comment]
我还以为官方用的自己的 require 不支持 import，会尽快处理

**Comment by chemzqm** [comment]
@Poordeveloper beta 版已加入 编译 es2015 的功能，我刚测试了可以支持 import 语法，欢迎试用：https://github.com/chemzqm/wept/wiki/WEPT-0.3.0-beta-%E6%B5%8B%E8%AF%95%E7%89%88

**Comment by Poordeveloper** [comment]
谢谢
