### ISSUE TITLE
微信小程序能同时当成app的客户端使用吗

### ISSUE THREAD

**Issue by lizhi2013** [chemzqm/wept#28]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

**Comment by chemzqm** [comment]
如果你说的是 wept 生成界面的话，结论是并不合适，因为没有打包优化，而且部分 API 是模拟的。
如果你想小程序做为自己 app UI 的话，则需要自己开发一整套兼容小程序的原生组件和构建方式。
