### ISSUE TITLE
页面的重定向问题

### ISSUE THREAD

**Issue by f111fei** [chemzqm/wept#33]
* `wept --version`:  3.0.0-beta

例如使用官方的默认项目， 项目中包含了一个logs的page ， 浏览器里面想直接打开该page

输入 http://127.0.0.1:3000/#!pages/logs/logs

结果会重定向到index page页， 这个行为和之前的表现不一致。 
这个问题比较严重希望尽快修复

**Comment by chemzqm** [comment]
新版使用了 sessionStorage 保存之前的路由路径以便刷新后重现之前的页面，我这里加个判定可以解决这个问题。

**Comment by chemzqm** [comment]
修复了，只是这种直接进入的方式我没办法渲染之前的页面，因为现在小程序的 pages 的定义方式我是无法知道之前的页面有哪些的，所以用户会没办法返回，我觉得加个 home 按钮会好一些

**Comment by f111fei** [comment]
感谢， 我这边如果是直接进入的，暂时不需要返回HOME这个选项，之前如果要返回到HOME可以点一下那个下拉列表的刷新按钮。
