### ISSUE TITLE
能否启动服务时指定服务IP，在真机上进行连接测试

### ISSUE THREAD

**Issue by yuzhewo** [chemzqm/wept#35]
例如 wept -h 192.168.1.102 -p 3000 通过手机进行扫码在真机进行预览，不知道此种情况能否做到时时刷新。

**Comment by chemzqm** [comment]
可以的，我弄个我二维码扫码的界面。

**Comment by chemzqm** [comment]
![1](https://cloud.githubusercontent.com/assets/251450/19597319/60d29a14-97c6-11e6-9ffd-cb22c7fc63b4.jpeg)
bu yong zhi ding 不用指定 ip 的，后台可以获取到。
