### ISSUE TITLE
Error: EMFILE: too many open files,

### ISSUE THREAD

**Issue by yanhuayu** [chemzqm/wept#36]
* `wept --version`: 
0.3.25
* `node --version`: 

* 操作系统: 
win10
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
listening on port 3000                                                                                                                                                    
Error: EMFILE: too many open files, open 'E:\Code\WxApp\WEPTest\node_modules\lodash\_baseDifference.js'                                                                   
    at Error (native)

**Comment by chemzqm** [comment]
@yanhuayu 你尝试下去掉你自己项目里的 node_modules 目录看看是否还有个报错，我确认下这个问题是不是因为项目下 js 文件过多导致的

**Comment by chemzqm** [comment]
可以试下 0.3.8 很可能不会再报错了
