### ISSUE TITLE
关于绘图问题

### ISSUE THREAD

**Issue by qssq** [chemzqm/wept#40]
* `wept --version`: 不清楚运行 后是1028的。今天更新的版本
* `node --version`: 
* 操作系统: window7
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

        var context = wx.createContext();
        context.setStrokeStyle("#ff0000");
        context.setLineWidth(5);
        context.moveTo(30, 0);
        context.lineTo(360, 0); //x坐标 y坐标 如果要画一条横线 x坐标 那么 50  y 0
        context.stroke();

        //画一个矩形 距离 左边50 距离顶部 100  高宽 为150  填充色 为 0094ff
        context.rect(50, 100, 150, 150); //x y width height;
        context.setFillStyle("#0094ff");
        context.fill();
        //画一个 描边矩形
        context.rect(0, 0, 30, 30);
        context.stroke(); //这个描边貌似 对 上面的也生效了 

        //所以要用到路径 开始和结束路径都要写
        context.beginPath();
        context.rect(50, 50, 30, 30);
        context.setStrokeStyle("#876833");
        context.stroke();
        context.closePath();
        //再不用路径 话看看颜色变成啥了 发现颜色已经变成了路径之后的颜色了。  在距离屏幕顶部50 然后画一个横线 宽为5
        context.moveTo(0, 50);
        context.lineTo(5, 50);
        context.stroke(); //
        //画一个一模一样大的然后再画个 缩放的  距离 左边60 距离 屏幕顶部 60  填充颜色颜色为 绿色 以及一个  黑色
        var width = 50,
            height = 50;
        var x = 90,
            y = 90; //
        cotnext.beginPath();
        context.rect(50, 50, 90, 90);
        context.setFillStyle("#0000ff");
        context.fill();
        context.stroke();
        context.closePath();
        wx.drawCanvas({ canvasId: "1", actions: context.getActions() });

是我写错了吗 最后面的绘制不成功。 开始路径和关闭路径无效了。我懵逼了。然后在一改实时预览都不生效了。 更加懵逼了。

**Comment by qssq** [comment]
总而言之，就是 不要企图通过闭合现有路径来开始一条新路径 ，而开始一条新路径，以前的路径也不会闭合。 

程序语法问题最懵逼了， 请问自动提示的快捷键叫啥 ，比如wx.showTaost();光标选中toast()里面 在eclipse或者android studio可以按alt+/提示参数什么的。

**Comment by chemzqm** [comment]
@qssq 1028 的版本我还没发出来，你用的可能是别人改过的吧？我过几天会发新版本。
自动提示是你的编程工具提供的，这个要看你用啥编程工具了，wept 只是实时运行环境。
绘图那块官方改过 API，wept 暂时还没有同官方一致。

**Comment by chemzqm** [comment]
@qssq `cotnext.beginPath();` 你拼错了，用下 eslint 吧，可以画出来的。

**Comment by qssq** [comment]
我丢，竟然不报错。 谢谢了

**Comment by qssq** [comment]
没拼写错误呀，我用的是白鹭的。里面有你的联系方式。。。。哈哈。
