### ISSUE TITLE
https接口证书问题

### ISSUE THREAD

**Issue by yangg** [chemzqm/wept#41]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
Error: Hostname/IP doesn't match certificate's altnames: "Host: xx.com. is not in the cert's altnames: DNS: xxx.com" 
希望可以忽略https证书错误。

**Comment by yangg** [comment]
可能是另一个问题是引起，我的接口需要走代理，因为现在转发了接口，就用不了代理了。

**Comment by chemzqm** [comment]
@yangg 只在请求这边忽略错误没有用吧，因为服务器验证不过是不会返回结果的。我需要让 wept 支持配置代理接口。

**Comment by yangg** [comment]
textaea 是不支持autoheight么，直接不显示。

**Comment by chemzqm** [comment]
@yangg 新版兼容还没做完，今天晚些发布新版应该就可以显示了，但是官方的 textarea 本身并不完善。

**Comment by chemzqm** [comment]
textarea 我测试没问题了，新版 wept 添加了代理配置支持，请参考文档 https://github.com/chemzqm/wept/wiki/wept-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6 进行配置。
