### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by jonlus** [chemzqm/wept#42]
* `wept --version`: 0.3.8
* `node --version`: 6.9.1
* 操作系统: window10
* 浏览器及浏览器版本: chrome  
* 与官方工具表现不一致？
按照你提示的方法安装完wept  dos提示没有这命令，使用nmp安装时候报了2个警告 如日志中。

## 错误日志
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\wept\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

'wept' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chemzqm** [comment]
`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 `
这一行是不会影响年装的，应该是你 npm 的问题，执行：

    npm install npm@3.10.9 -g
    npm cache clean

没有 cache 可能需要稍微多等等。
