### ISSUE TITLE
weui for weapp demo 无法正常浏览

### ISSUE THREAD

**Issue by bluedazzle** [chemzqm/wept#43]
* `wept --0.3.8 101400`: 
* `node --6.0.0`: 
* 操作系统:  Mac OS X 10.11.4
* 浏览器及浏览器版本:  Chrome 56.0.2914.3 dev
* 与官方工具表现不一致？是

## 错误日志
无

## 原因
weui for weapp demo 中的下弹式菜单无法弹出导致无法浏览整个 demo，官方工具中正常。

https://github.com/weui/weui-wxss

**Comment by chemzqm** [comment]
@bluedazzle 0.4.0 版本应该可以了，刚发了新版本。

**Comment by chemzqm** [comment]
顺便说下，新版使用 wx.showToast wx.showModal wx.showActionsheet API 生成的元素是原生提供的，我们不能通过 css 改变它们的样式。

**Comment by chemzqm** [comment]
wxss 解析失败了，我研究下什么情况

**Comment by chemzqm** [comment]
他家的 wxss 支持 import 了，而且跟 wxml 一样是需要预先解析的
