### ISSUE TITLE
app.wxss 编译失败

### ISSUE THREAD

**Issue by lxrmido** [chemzqm/wept#45]
* `wept --version`: 0.5.0 103100
* `node --version`: v6.3.0

## 错误日志

listening on port 3000
 ✓ service.js build success
  <-- GET /
  --> GET / 200 23ms 1.22kb
  <-- GET /css/index.css?v=0.5.0
  <-- GET /css/app.css?v=0.5.0
  <-- GET /script/recorder.js?v=0.5.0
  --> GET /css/index.css?v=0.5.0 200 9ms 3.24kb
  --> GET /script/recorder.js?v=0.5.0 200 6ms 1.48kb
  --> GET /css/app.css?v=0.5.0 200 7ms 5.2kb
  <-- GET /script/build.js?v=0.5.0
  --> GET /script/build.js?v=0.5.0 200 27ms 105.27kb
  <-- GET /images/loading.gif
  --> GET /images/loading.gif 200 2ms 2.7kb
  <-- GET /appservice
  --> GET /appservice 200 12ms 1.34kb
  <-- GET /script/bridge.js?v=0.5.0
  <-- GET /script/service.js?v=0.5.0
  <-- GET /service.js
  --> GET /service.js 200 8ms 25.2kb
  --> GET /script/bridge.js?v=0.5.0 200 10ms 6.81kb
  --> GET /script/service.js?v=0.5.0 200 14ms 24.18kb
  <-- GET /app/pages/index/index.wxml?w=1920&r=1
  --> GET /app/pages/index/index.wxml?w=1920&r=1 200 21ms 2.6kb
  <-- GET /script/ViewBridge.js?v=0.5.0
  <-- GET /script/view.js?v=0.5.0
  <-- GET /app/app.wxss?w=1920&r=1
  <-- GET /app/pages/index/index.wxss?w=1920&r=1
  --> GET /script/ViewBridge.js?v=0.5.0 200 12ms 7.23kb
  --> GET /script/view.js?v=0.5.0 200 49ms 55.22kb
Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:255:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at Pipe.onread (net.js:542:20)
Error: app.wxss 编译失败，请检查
    at /usr/local/lib/node_modules/wept/build/parser.js:62:27
    at ChildProcess.exithandler (child_process.js:209:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by chemzqm** [comment]
你的 css 超过了 200kb，我调整下设置

**Comment by lxrmido** [comment]
嗯，临时加上maxBuffer可以编译了

**Comment by chemzqm** [comment]
0.5.1 已设置 maxBuffer 为  600kb
