### ISSUE TITLE
WEPT 请求时不检查安全域名? 

### ISSUE THREAD

**Issue by Mrlilili** [chemzqm/wept#47]
* `wept --version`: 0.5.5 112200
* `node --version`: 6.0.0
* 操作系统: win10
* 浏览器及浏览器版本: chrome  54.0.2840.99 m
* 与官方工具表现不一致？
报错不一致
## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/8361655/20614015/83ee913e-b304-11e6-9f70-ec24061c9ae3.png)

怀疑是安全域名的问题，我升级wept到最新版本就警告，接口请求无法发出，升级前的wept版本好像是0.3几

我把wept降到0.5.3就可以了。
降了之后有个问题，点击picker的时候会出现
![image](https://cloud.githubusercontent.com/assets/8361655/20616369/c85980e6-b31c-11e6-9e01-c433c87410cf.png)

官方工具不会出现

**Comment by chemzqm** [comment]
这不是报错，只是警告开发者 wept 并没有对安全域名进行检查，好像有点多余了.
picker 那个组件貌似我这边需要重新实现一下，最新版 wept 应该也是会发警告的。

**Comment by Mrlilili** [comment]
检查警告还好，但是直接拦截了，请求不了数据我需要的数据

**Comment by chemzqm** [comment]
0.5.6 已经紧急修复了这个 bug， 感谢反馈！

**Comment by Mrlilili** [comment]
更新0.5.6后
![image](https://cloud.githubusercontent.com/assets/8361655/20618890/79f9789c-b32c-11e6-92f4-50ded4e75514.png)

**Comment by chemzqm** [comment]
😢 代码加错地方了，看来有必要弄点自动测试的东西。
0.5.7 中应该没有问题了

**Comment by Mrlilili** [comment]
picker的那个问题还是存在，无法出现picker的选择层，控制台有一个警告
![image](https://cloud.githubusercontent.com/assets/8361655/20619562/28a1e3e0-b330-11e6-9d52-533abd68f386.png)
如果重新实现的话，那就等你新版本，或者你暂时用原先的那个picker可以保证正常显示嘛

**Comment by chemzqm** [comment]
没有原先的了，因为小程序内部调整了实现方式，这块现在由控制层实现。
我把他们代码弄过来就可以了

**Comment by chemzqm** [comment]
@Mrlilili 我刚实现了基础版的 picker，测试可以用了，日期的 pick 要过两天
