### ISSUE TITLE
添加对 scss 编译支持

### ISSUE THREAD

**Issue by fuchao2012** [chemzqm/wept#48]
* `wept --version`: 0.5.8 112200
* `node --version`: v6.7.0
* 操作系统: mac osc
* 浏览器及浏览器版本: 54.0.2840.98 (Official Build) (64-bit)
* 与官方工具表现不一致？

引入第三方编译好的 css 样式库时，出现编译 不过 '\' "media-qurey" 等问题，wcsc

**Comment by chemzqm** [comment]
WEPT 的编译部分使用的是官方工具 wcsc，如果它不支持对应的 css 语法，我这边也不会处理，需要你自己去掉这部分 css。

**Comment by fuchao2012** [comment]
多谢告知，当时的场景是，引入了第三方的 CSS 库，其中有些兼容性处理就编译不通过。后来找到了 weui-wxss 版本，可以直接 import 成功。

算是个小坑吧。

@chemzqm 有木有其他的第三方库引入方式（：

**Comment by chemzqm** [comment]
官方的已经做的很好的，其它的未必完全兼容小程序的 wxss，所以很可能上线后出现严重问题，不建议使用。其它引入方式暂时应该是没有的。
