### ISSUE TITLE
service.js?v=0.5.9:3430 Uncaught TypeError: Cannot read property '__core-js_shared__' of undefined(…)

### ISSUE THREAD

**Issue by Gcaufy** [chemzqm/wept#50]
* `wept --version`: 0.5.9 112200
* `node --version`: v7.0.0
* 操作系统: WIN7
* 浏览器及浏览器版本: Chrome
* 与官方工具表现不一致？

## 错误日志
service.js?v=0.5.9:3430 Uncaught TypeError: Cannot read property '__core-js_shared__' of undefined(…)

## 界面截图（可选）

wept: 
![20161205](https://cloud.githubusercontent.com/assets/2182004/20887619/5d760606-bb36-11e6-9cde-483e7ca46bce.jpg)

开发者工具：
![image](https://cloud.githubusercontent.com/assets/2182004/20887623/674f2f2c-bb36-11e6-94cc-06fb7037da33.png)

因为引入了babel-runtime，导致部分代码在wept中不工作，这份代码是在手机端和开发者工具都运行通过的，却在wept运行失败了。。

DEMO:

```bash
npm install wepy-cli -g
wepy new demo
cd demo
wepy build
cd dist
wept
```

**Comment by chemzqm** [comment]
严格模式的问题，wept 总是使用 es6 进行编译的，所以 this 是 undefined。
要么你在使用 wept 的时候不用 babel，要么 wept 提供一个不使用 babel 的选项？

**Comment by huike1989** [comment]
我也遇到这个问题，wept是否可以提供一个 不默认使用babel 编译的选项，毕竟在chrome es6的特性基本都是支持的吧。

**Comment by Gcaufy** [comment]
@chemzqm 那希望能像开发者工具一样，提供一个ES6可选的选项，谢谢。

**Comment by chemzqm** [comment]
@huike1989 使用 babel 主要是为了尽可能保持跟官方实现一致。

@Gcaufy 0.6.0 已支持通过 wept.json 关闭 babel 编译。

**Comment by huike1989** [comment]
@chemzqm 刚更新啦  0.6.0版本？怎么关闭babel编译呢？

**Comment by chemzqm** [comment]
https://github.com/chemzqm/wept/wiki/wept-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by Gcaufy** [comment]
多谢~~
