### ISSUE TITLE
wept.json {babel: false}  不生效

### ISSUE THREAD

**Issue by huike1989** [chemzqm/wept#51]
* `wept --version`: v 0.6
* `node --version`: v6.3
* 操作系统:  windows
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
wept.json {babel：false}  这个选项。我在npm更新下来发现还是无效。但是我直接从你的git上面拉取wept/lib代码 覆盖 wept/build中代码生效。我对比了下文件，发现npm 更新的 parse.js中 确实 没有config.babel的代码。

**Comment by chemzqm** [comment]
@huike1989 发布前忘记 build 了，这锅 npm 背一半，这货的 prepublish hook 没法用，因为安装时也会执行。
