### ISSUE TITLE
wxss使用相对路径报错

### ISSUE THREAD

**Issue by huike1989** [chemzqm/wept#52]
* `wept --version`: 0.6.1
* `node --version`: V6.8
* 操作系统: win7
* 浏览器及浏览器版本: chrome
* 与官方工具表现不一致？是的

## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/7878971/21043869/03824ece-be34-11e6-854d-851b1951600a.png)

**Comment by chemzqm** [comment]
@huike1989 需要你提供下 cell.wxss 这个文件，报错原因是 avatar.wxss 没有被预解析出来。

**Comment by chemzqm** [comment]
遗漏了递推解析 wxss，会尽快修复

**Comment by chemzqm** [comment]
请试用 0.6.2， 如果还有问题再 reopen
