### ISSUE TITLE
.wxss路径bug

### ISSUE THREAD

**Issue by huike1989** [chemzqm/wept#54]
wept --version: 0.6.3
node --version: V6.8
操作系统: win7
浏览器及浏览器版本: chrome
与官方工具表现不一致？是的
## 错误日志
wxss 寻找的路径不对，官方工具是可以的。

## 界面截图（可选）
报错信息：
![image](https://cloud.githubusercontent.com/assets/7878971/21077876/f1c19f5c-bf94-11e6-9cb6-1c9de8c8a3c2.png)
代码结构：
![image](https://cloud.githubusercontent.com/assets/7878971/21077879/1a627706-bf95-11e6-898b-49ba4355bc75.png)

**Comment by chemzqm** [comment]
感谢反馈，正在排查中。

**Comment by xyyjk** [comment]
@huike1989 

资源的引入用绝对路径更方便些： `@import "/components/cell.wxss";`
