### ISSUE TITLE
升级至 0.6.4 版本使用绝对路径引入错误

### ISSUE THREAD

**Issue by xyyjk** [chemzqm/wept#56]
* `wept --version`: 0.6.4
* `node --version`: 6.3.1
* 操作系统: macOS Sierra
* 浏览器及浏览器版本: chrome 55
* 与官方工具表现不一致？
升级至`0.6.4` 版本后 wxml 中用绝对路径引入的模板出现路径错误提示
用绝对路径（@import "/tmpl/react.wxss";）引入的 wxss 同样有该问题

之前用的 0.5.9版本无此问题

## 错误日志
```
ENOENT: no such file or directory, open 'view/index/tmpl/react.wxml'
Error: ENOENT: no such file or directory, open 'view/index/tmpl/react.wxml'
    at Error (native)
```

## 界面截图（可选）
![dingtalk20161212104443](https://cloud.githubusercontent.com/assets/2508421/21086553/9125b452-c058-11e6-99f7-cb815fbf9bdc.png)
<img width="562" alt="dingtalk20161212104402" src="https://cloud.githubusercontent.com/assets/2508421/21086554/9126e8ea-c058-11e6-8e74-0cc576cdc07b.png">
<img width="427" alt="dingtalk20161212104126" src="https://cloud.githubusercontent.com/assets/2508421/21086555/912783b8-c058-11e6-91f6-32ed3df6ec5c.png">

**Comment by xyyjk** [comment]
两个文件的路径是：
```
view/index/index.wxml
tmpl/react.wxml
```

**Comment by chemzqm** [comment]
@xyyjk 感谢反馈
