### ISSUE TITLE
获取手机系统信息 都只有一个固定值 并不会随着切换设备而改变

### ISSUE THREAD

**Issue by SuperKieran** [chemzqm/wept#6]
* `wept --version`: 0.2.3
* `node --version`: 6.4.0
* 操作系统: MacOS
* 浏览器及浏览器版本: Chrome 53.0.2785.143 (64-bit)
* 与官方工具表现不一致？
获取手机系统信息 都只有一个固定值 并不会随着切换设备而改变
https://mp.weixin.qq.com/debug/wxadoc/dev/api/device.html#wxgetsysteminfoobject  
比如 windowWidth 永远是320，切换设备也是320 明显不对
model 永远是iPhone 6

**Comment by chemzqm** [comment]
是的，这块当时直接写死了，我原以为官方也是写死的，会尽快调整。

**Comment by chemzqm** [comment]
@SuperKieran 已在 0.2.4 版本修复
