### ISSUE TITLE
菜单点击没反应

### ISSUE THREAD

**Issue by hellopao** [chemzqm/wept#60]
在打开开发者工具的时候点这个菜单是没反应的，切换到触屏设备的时候就可以点。看了下代码，那个actionsheet里只绑定了touch事件，没绑click事件，这个能支持一下不。感谢！
![image](https://cloud.githubusercontent.com/assets/5064875/21209675/a10a3e92-c2b0-11e6-98d6-f745c5ed447f.png)

**Comment by chemzqm** [comment]
@hellopao 你用的是什么开发者工具？这个工具应该开启 chromium 的移动端模式，此时是有 touch 事件的，如果没有 touch 事件，不管这个菜单，其它弹出层例如 picker 和 actionsheet 以及下滑的事件也都无法触发的。
我觉得这是开发工具的问题。

**Comment by hellopao** [comment]
@chemzqm 我用wept是来做vscode里面小程序实时预览的插件，里面是用iframe内嵌的wept生成的页面，发现菜单点不了，用chrome开发者工具调试的时候发现绑的是touch事件，vscode的机制现在是不支持触屏模拟的，所以看你能不能加个click事件。

**Comment by chemzqm** [comment]
@hellopao 我把这个菜单的事件改下，没想到 vscode 这么挫

**Comment by hellopao** [comment]
@chemzqm :+1:
