### ISSUE TITLE
ubuntu下wxss文件编译失败

### ISSUE THREAD

**Issue by leinue** [chemzqm/wept#62]
* `wept --version`: 0.6.9 112200
* `node --version`: v6.9.2
* 操作系统: ubuntu
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志

Error: Command failed: wine /root/.nvm/versions/node/v6.9.2/lib/node_modules/wept/bin/wcsc.exe -lc -db ./app.wxss ./style/weui.wxss ./style/base/reset.wxss ./style/widget/weui-cell/weui-cell.wxss ./style/widget/weui-cell/weui-access.wxss ./style/widget/weui-cell/weui-check.wxss ./style/widget/weui-cell/weui-form.wxss ./style/widget/weui-cell/weui-switch.wxss ./style/widget/weui-cell/weui-uploader.wxss ./style/widget/weui-page/weui-article.wxss ./style/widget/weui-page/weui-msg.wxss ./style/widget/weui-flex/weui-flex.wxss ./style/widget/weui-button/weui-button.wxss ./style/widget/weui-agree/weui-agree.wxss ./style/widget/weui-footer/weui-footer.wxss ./style/widget/weui-grid/weui-grid.wxss ./style/widget/weui-loading/weui-loading.wxss ./style/widget/weui-tips/weui-badge.wxss ./style/widget/weui-tips/weui-loadmore.wxss ./style/widget/weui-panel/weui-panel.wxss ./style/widget/weui-media-box/weui-media-box.wxss ./style/widget/weui-progress/weui-progress.wxss ./style/widget/weui-tab/weui-tab.wxss ./style/widget/weui-searchbar/weui-searchbar.wxss ./style/base/fn.wxss ./style/widget/weui-cell/weui-form/weui-form_common.wxss ./style/widget/weui-cell/weui-form/weui-form-preview.wxss ./style/widget/weui-cell/weui-form/weui-select.wxss ./style/widget/weui-cell/weui-form/weui-vcode.wxss ./style/widget/weui-tab/weui-navbar.wxss ./style/base/mixin/setOnepx.wxss ./style/base/mixin/setArrow.wxss ./style/base/mixin/text.wxss ./style/base/variable/global.wxss ./style/base/variable/color.wxss ./style/base/variable/weui-cell.wxss ./style/base/variable/weui-button.wxss ./style/base/variable/weui-msg.wxss ./style/base/variable/weui-grid.wxss ./style/base/variable/weui-progress.wxss ./style/base/variable/weui-dialog.wxss
ERR: ./style/base/fn.wxss(2:1): unexpected token `@import`
./style/base/mixin/setArrow.wxss(11:15): unexpected `(` at pos 338
./style/base/mixin/setOnepx.wxss(1:13): unexpected token `(`
./style/base/mixin/text.wxss(1:11): unexpected token `(`
./style/base/variable/color.wxss(2:20): unexpected token `#1AAD19`
./style/base/variable/global.wxss(2:32): unexpected token `"Helvetica Neue"`
./style/base/variable/weui-button.wxss(1:20): unexpected token `15px`
./style/base/variable/weui-cell.wxss(13:90): unexpected `�` at pos 404
./style/base/variable/weui-dialog.wxss(1:29): unexpected token `#FFFFFF`
./style/base/variable/weui-grid.wxss(1:22): unexpected token `#D9D9D9`
./style/base/variable/weui-msg.wxss(1:20): unexpected token `36px`
./style/base/variable/weui-progress.wxss(1:18): unexpected token `#EBEBEB`
./style/widget/weui-button/weui-button.wxss(5:5): unexpected `&` at pos 83
./style/widget/weui-cell/weui-access.wxss(9:5): unexpected `&` at pos 154
./style/widget/weui-cell/weui-cell.wxss(8:41): unexpected `�` at pos 220
./style/widget/weui-cell/weui-check.wxss(15:5): unexpected `&` at pos 242
./style/widget/weui-cell/weui-form/weui-form-preview.wxss(6:5): unexpected `&` at pos 114
./style/widget/weui-cell/weui-form/weui-form_common.wxss(9:15): unexpected `(` at pos 156
./style/widget/weui-cell/weui-form/weui-select.wxss(17:5): unexpected `&` at pos 330
./style/widget/weui-cell/weui-form/weui-vcode.wxss(22:5): unexpected `&` at pos 598
./style/widget/weui-cell/weui-uploader.wxss(32:5): unexpected `&` at pos 702
./style/widget/weui-footer/weui-footer.wxss(24:5): unexpected `&` at pos 438
./style/widget/weui-grid/weui-grid.wxss(17:5): unexpected `&` at pos 423
./style/widget/weui-media-box/weui-media-box.wxss(6:5): unexpected `&` at pos 97
./style/widget/weui-panel/weui-panel.wxss(7:5): unexpected `&` at pos 104
./style/widget/weui-searchbar/weui-searchbar.wxss(3:23): unexpected token `28px`
./style/widget/weui-tab/weui-navbar.wxss(21:5): unexpected `&` at pos 352
./style/widget/weui-tips/weui-loadmore.wxss(32:5): unexpected `&` at pos 615

**Comment by leinue** [comment]
没有问题了 在weui-wxss的dist文件夹下编译通过了

**Comment by chemzqm** [comment]
weui-wxss 项目的 src 下的 wxss 使用的 less 语法，肯定编译不过的。
