### ISSUE TITLE
希望可以添加https支持

### ISSUE THREAD

**Issue by NorthKou** [chemzqm/wept#63]
当前node server为http形式，在chrome中无法调用位置共享服务。

希望可以提供配置，将node server设置为https形式。

参考资料：
[websocket-with-ssl](http://stackoverflow.com/questions/9745249/html5-websocket-with-ssl)

**Comment by chemzqm** [comment]
这个事不适合 wept 来做，如果你需要 https 可以自己本机配置 nginx 反向代理 wept 的请求，自己配置证书信息，这样更灵活一些。

**Comment by NorthKou** [comment]
<img width="554" alt="2017-01-04 2 03 08" src="https://cloud.githubusercontent.com/assets/21114638/21633344/46cc2718-d289-11e6-8dcf-f93f80aa8f4c.png">

chrome会报这个错误。是不是需要使用wss来通信才可以。
这个错误在firefox也一样会报。

**Comment by NorthKou** [comment]
nginx 配置如下：

server {
    listen 443;
    listen [::]:443;

    server_name wechat.ucartest.com;

    ssl on;
    ssl_certificate /vmdata/nginx/cert/server.crt;
    ssl_certificate_key /vmdata/nginx/cert/server.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers "HIGH:!aNULL:!MD5";
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:3000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

**Comment by chemzqm** [comment]
是的，websocket 也需要使用 wss 才可以，我可以加个配置，让 websocket 使用 wss 请求

**Comment by NorthKou** [comment]
多谢。
