### ISSUE TITLE
官方工具升级了，大概什么时候能更新？

### ISSUE THREAD

**Issue by zaaack** [chemzqm/wept#64]
求问大概什么时候能更新？或者提供一下大概的更新方式也行，只看到 make update 可以把一些ide里的文件拷贝出来，但是不知道怎么用？

**Comment by chemzqm** [comment]
很快，我先看看他们更新了啥

**Comment by zaaack** [comment]
改动蛮大的：https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html?t=20161221

**Comment by chemzqm** [comment]
确实蛮多的，估计要过个一两周我才能都同步过来

**Comment by zaaack** [comment]
虽然过几天就得用了，可能还得自己手动写点patch，不过还是顺便感谢下作者哈

**Comment by chemzqm** [comment]
已经在弄了， 微信那边改了一些内部实现，比较麻烦。

**Comment by chemzqm** [comment]
@zaaack 更新了，除了 scanCode 都可以支持了

**Comment by zaaack** [comment]
😲 作者神速啊！
