### ISSUE TITLE
最新版 wx.previewImage 貌似不能滚动

### ISSUE THREAD

**Issue by zaaack** [chemzqm/wept#65]
* `wept --version`: 0.7.0-beta
* `node --version`: v6.3.1
* 操作系统:  macOS
* 浏览器及浏览器版本:  chrome 54 移动模式和 miui 浏览器
* 与官方工具表现不一致？
官方工具的wx.previewImage 可以滚动，但是wept 的不能
## 错误日志
无

## 界面截图（可选）
<img src="https://cloud.githubusercontent.com/assets/5233940/21448056/0f501b2e-c919-11e6-8bac-1a9cb6737f6a.png" width="320" />

**Comment by chemzqm** [comment]
imagePreview 需要 touch 事件支持

**Comment by zaaack** [comment]
我可能没说清楚，我在手机和chrome 移动模拟器中测试的，之前是可以的，但是现在不可以了

**Comment by chemzqm** [comment]
@zaaack 我本地测试没问题的， 你可以 clone 一下这个项目，然后在 case 目录下使用 wept，打开

http://localhost:3000/#!features/imagePreview

测试下，我怀疑可能是你 app.json 里面配置了什么导致。

**Comment by zaaack** [comment]
@chemzqm 额，这个bug是npm最新版0.6.9才这样，如果是 master 分支最新则完全空白。。

项目地址是：https://github.com/Asshai/topic

**Comment by zaaack** [comment]
@chemzqm 弄了半天没发现原因，如果切换回之前的老版本wept就是正常的了

**Comment by chemzqm** [comment]
我没有动 images-preview 组件，可以是跟官方代码事件处理有冲突了。

**Comment by zaaack** [comment]
@chemzqm 然而这都是小问题，最严重的是master分支打开我的那个项目直接空白。。空白的时候也不报错

**Comment by chemzqm** [comment]
https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html 应该是微信方面代码问题，等我更新代码。。

**Comment by zaaack** [comment]
嗯嗯，谢了哈～

**Comment by chemzqm** [comment]
空白是两次 setData 导致的，我这里的处理需要改进下。

**Comment by chemzqm** [comment]
它们改进了内部架构实现，数据处理从 service 层完全挪动到了控制层，我这儿也需要进行大的调整。

**Comment by zaaack** [comment]
@chemzqm 有啥更新吗？有没有临时的 hack 一点的解决办法？

**Comment by zaaack** [comment]
刷那么十多次偶尔有一次能正常显示。。总给人一种胜利就在眼前的感觉。。

**Comment by zaaack** [comment]
刷多次偶尔可以刷出这种错误。。![image](https://cloud.githubusercontent.com/assets/5233940/21475228/0fb84b16-cb64-11e6-8e65-6dc8e8b197a6.png)

**Comment by chemzqm** [comment]
setData 完全不可用了，控制层逻辑需要重新实现

**Comment by zaaack** [comment]
@chemzqm 好吧。。

**Comment by chemzqm** [comment]
<img width="426" alt="screen shot 2016-12-26 at 3 58 12 pm" src="https://cloud.githubusercontent.com/assets/251450/21478290/cced4b62-cb84-11e6-90e3-c22491c3910e.png">
定位到原因了，他们的 WebviewIds 会在 number 和 string 之间切换形态，简直坑爹。

**Comment by zaaack** [comment]
@chemzqm  👍

**Comment by chemzqm** [comment]
可以使用 0.7.0-b1 版本，我测了你的项目，渲染的问题已经修复了。

**Comment by zaaack** [comment]
@chemzqm 好的，多谢了🙏

**Comment by zaaack** [comment]
@chemzqm 貌似并没有好转啊。。

**Comment by zaaack** [comment]
个人感觉和两个部分加载时间差有关，可能 在发布事件的时候 iframe 还没加载导致事件丢失和页面没有渲染，不过没有代码支持，纯属猜想。。

**Comment by chemzqm** [comment]
@zaaack 请确认你的 wept 版本
```
❯ wept -V
0.7.0-b1 122100
```
我刚试了 一切正常

**Comment by zaaack** [comment]
@chemzqm 
![image](https://cloud.githubusercontent.com/assets/5233940/21479644/f92d538c-cb90-11e6-93f3-e324505db2d2.png)

**Comment by chemzqm** [comment]
你需要手工安装 beta 版本

    npm i -g wept@0.7.0-b1

然后输入`wept -V` 确认升级成功

**Comment by zaaack** [comment]
我是 pull master , 然后 npm link 的

**Comment by chemzqm** [comment]
pull master 必须每次 pull 完之后执行 `gulp prepublish` 或者 `gulp build` 编译前后端的代码。

**Comment by zaaack** [comment]
@chemzqm 额，好吧。。我看编译目录没忽略掉，还以为是最新的编译。。

**Comment by zaaack** [comment]
@chemzqm 果然好了,赞！
