### ISSUE TITLE
增加初始化小程序功能

### ISSUE THREAD

**Issue by Jax0rz** [chemzqm/wept#67]
能否新增一个指令比如:
`wept --init`(初始化基本的小程序目录结构和配置文件)
(参考[微信小程序在线生成工具](https://weapptool.com/start.html)的功能)

**Comment by chemzqm** [comment]
可以考虑

**Comment by Jax0rz** [comment]
我根据微信官方模版弄了一个微信小程序的初始化模版，这是[shell脚本](https://github.com/Jax0rz/WeChatQuickStart)，这是[初始化文件](https://github.com/Jax0rz/wechatappquickstarter)
