### ISSUE TITLE
浏览器预览即使最外层有overflow:hidden，依然有滚动条

### ISSUE THREAD

**Issue by treadpit** [chemzqm/wept#68]
* `wept --最新版`: 
* `node --6.30`: 
* 操作系统: mac
* 浏览器及浏览器版本: chorme  55.0.2883.95 (64-bit)

## bug描述
浏览器出现滚动条，小程序程序最外层view已经设置了overflow:hidden,加上important也不行，这个是正常的么，专门这么设置的？

## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/10692855/21560120/775f241e-ce94-11e6-82b7-0fb99bd546a3.png)
![image](https://cloud.githubusercontent.com/assets/10692855/21560125/8504d0c8-ce94-11e6-9a4d-00e8235ea29c.png)

**Comment by chemzqm** [comment]
chrome 偶尔会出现这个问题，一般刷新下就好了，那个地方必须设置 scroll，不然页面无法正常滚动。
