### ISSUE TITLE
在input的value中绑定的数据如果没有初始值会显示成undefined

### ISSUE THREAD

**Issue by giyyapan** [chemzqm/wept#69]
* `wept --version`: 0.6.9 112200
* `node --version`: v5.5.0
* 操作系统: osx
* 浏览器及浏览器版本:  chrome 55
* 与官方工具表现不一致？ 不一致

微信官方工具无初值时会解析成空字符串而非‘undefined’

**Comment by chemzqm** [comment]
0.7.0 版没有这个问题，建议更新。
