### ISSUE TITLE
wxml中input和require标签的src属性如果路径没有带.wxml后缀会报错

### ISSUE THREAD

**Issue by giyyapan** [chemzqm/wept#70]
* `wept --version`: 0.6.9 112200
* `node --version`: v5.5.0
* 操作系统: osx
* 浏览器及浏览器版本: chrome 55
* 与官方工具表现不一致？不一致
官方工具在wxml中允许inlcude和require的src不带.wxml后缀

**Comment by chemzqm** [comment]
会尽快修复。
