### ISSUE TITLE
wx.uploadFile的返回值中没有携带data字段

### ISSUE THREAD

**Issue by giyyapan** [chemzqm/wept#71]
* `wept --version`: 0.6.9 112200
* `node --version`: v5.5.0
* 操作系统:  osx
* 浏览器及浏览器版本: chrome 55
* 与官方工具表现不一致？不一致

根据[官方文档](https://mp.weixin.qq.com/debug/wxadoc/dev/api/network-file.html?t=201715#wxuploadfileobject)，在调用wx.uploadFile之后可以在success的回调参数里面取到data这个字段，其中包含了上传api调用后的返回值，官方调试工具的行为和文档一致
但是在wept中会找不到这个返回值字段

是wept没有办法模拟官方工具上传操作吗？

**Comment by chemzqm** [comment]
不是，有两种可能，一是我实现时候漏掉了，二是这个返回字段是新版加上的，我没注意到。
