### ISSUE TITLE
wx对象缺失switchTab方法

### ISSUE THREAD

**Issue by funemy** [chemzqm/wept#72]
* `wept --version`: 0.6.9 112200
* `node --version`: 5.8.0 / 6.7.0
* 操作系统: mac OS
* 浏览器及浏览器版本: chrome 55
* 与官方工具表现不一致？不一致

## bug描述
wx对象缺失switchTab方法， 但如navigateTo等可用

## 界面截图（可选）
<img width="397" alt="screen shot 2017-01-05 at 2 55 42 pm" src="https://cloud.githubusercontent.com/assets/5792751/21670402/1b5c0246-d357-11e6-9946-6afb61163a43.png">

**Comment by chemzqm** [comment]
@funemy 这个方法在 0.7.0 中实现了，需要手工执行：
```
npm i wept@0.7.0-b1 -g
```
来安装。

目前处于测试功能并不完善，给您造成的不便敬请谅解，如有问题欢迎及时反馈。
