### ISSUE TITLE
Linux wine 使用

### ISSUE THREAD

**Issue by gucong3000** [chemzqm/wept#75]
Linux 下的环境搭建不是很明白。作者能否给一篇wiki简单介绍一下？
我这边是希望在CI服务器上运行单元测试。

**Comment by chemzqm** [comment]
包管理器安装下就行了，不太需要文档吧。
你可以参考 https://github.com/wetools/wept-build/blob/master/.travis.yml 这个文件

**Comment by gucong3000** [comment]
多谢，正是我所需要的
