### ISSUE TITLE
好像创建页面太多有限制

### ISSUE THREAD

**Issue by whfandtank** [chemzqm/wept#76]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

## 错误日志
现在只能创建五个页面然后就创建不了，能否去掉这个限制

**Comment by chemzqm** [comment]
不是5个页面，是页面深度到 5 ，这是小程序规定的显示，改为弹出提醒好了

**Comment by chemzqm** [comment]
已调整为 console.warn
