### ISSUE TITLE
延展操作符编译不通过

### ISSUE THREAD

**Issue by wangbagang** [chemzqm/wept#77]
* `wept --version`: 最新版
* `node --version`: 最新版
* 操作系统: win7
* 浏览器及浏览器版本: chrome最新版
* 与官方工具表现不一致？

## 错误日志
case REQUEST_POSTS:
      return {
        ...state,
        isFetching: true,
        didInvalidate: false
      }
编译错误
[16:53:31] gulp-notify: [Error running Gulp] SyntaxError in plugin 'gulp-babel'
Message:
    E:/workspace/wxapp-meum/src/redux/models/mall.js:
Unexpected token (30:4)

**Comment by chemzqm** [comment]
object-rest-spread 是在 staging 里面的规范，不属于 es2015，官方工具也不支持，这里 WEPT 会保持与官方一致。
我不太建议使用 redux 方式在小程序中管理数据流：
其一，与 react 不同，redux 里的数据变动不能直接反射到 UI 变化
其二，小程序本身提供了 data 的统一管理以及控制台插件，加入 redux 会额外增加管理成本。

**Comment by wangbagang** [comment]
谢谢，自己修改可以支持了，不过你说的第一条，redux里的数据变动当然是可以反射到UI变化的，不然肯定不会用redux的。

**Comment by vivaxy** [comment]
目前微信官方编辑器支持了 Object spread 操作符。请问 wept 会支持吗？

**Comment by wind4gis** [comment]
不知道楼主怎么处理的 @wangbagang 我这里也提示...报错了，但是升级babel至最新版本还是不能识别

**Comment by ldwonday** [comment]
@wind4gis 已经放弃这个工具了
