### ISSUE TITLE
使用后台转发 XMLHttpRequest 请求，无需配置 CORS

### ISSUE THREAD

**Issue by b1g3rr0r** [chemzqm/wept#8]
* `wept --0.2.3`: 
* `node --6.0.0`: 
* 操作系统: MacOS 10.12

## 错误日志
wx.request 一个请求，还是提示
URL 域名不合法，请在 mp 后台配置后重试

需要有什么配置嘛？

**Comment by chemzqm** [comment]
@b1g3rr0r 这个是升级官方 101400 引入的 bug，最新版本 0.2.5 已修复这个问题。你需要：

    npm update wept -g 

更新

**Comment by b1g3rr0r** [comment]
![45e284e5-a273-460c-8d1c-e829389c16e1](https://cloud.githubusercontent.com/assets/20431351/19425300/5c21b09c-9463-11e6-8c1d-86c02c4e73bc.png)
刚更新完，这个提示。
````
onReady: function () {
    wx.request({
      url: 'https://api.douban.com/v2/movie/in_theaters',
      success: function (res) {
        console.log(res.data)
      }
    })
  }
````

**Comment by chemzqm** [comment]
后端代理的问题，应该是没有 https 的支持，我下午想办法解决下。

**Comment by chemzqm** [comment]
@b1g3rr0r 我测试已经可以请求 https 了，但是豆瓣那边对请求做了更严格的验证，我正在处理。

**Comment by chemzqm** [comment]
新建了 #9 issue，这个先关闭了
