### ISSUE TITLE
pullDownToRefresh不好使了

### ISSUE THREAD

**Issue by Poordeveloper** [chemzqm/wept#80]
好像是官方ide的pullDownToRefresh也不好使了

**Comment by chemzqm** [comment]
我这里测试是没问题的，可能是你的元素阻止了 touchmove 事件冒泡，也可能是你设置了元素 position为 fixed 或者 absoluted 挡住了下拉刷新的元素。

**Comment by Poordeveloper** [comment]
原来是因为sroll-view

**Comment by chemzqm** [comment]
https://mp.weixin.qq.com/debug/wxadoc/dev/component/scroll-view.html
