### ISSUE TITLE
加载页面后，js报__core-js_shared__未定义，打不开页面

### ISSUE THREAD

**Issue by geeyan** [chemzqm/wept#81]
* `wept --version`: 0.8.0 130400
* `node --version`: v6.5.0
* 操作系统: MacOS X 10.11.6 (15G1108)
* 浏览器及浏览器版本: Chrome/55.0.2883.95
* 与官方工具表现不一致？

## 错误日志
![image](https://cloud.githubusercontent.com/assets/4083759/22300844/d1a08b0a-e363-11e6-93d2-9a8b0955b229.png)

## 界面截图（可选）
监听是正常的：
![image](https://cloud.githubusercontent.com/assets/4083759/22300831/c40333ee-e363-11e6-832d-5b1cc9963a18.png)
界面是空白的：
![image](https://cloud.githubusercontent.com/assets/4083759/22300886/f14b5c6e-e363-11e6-9bdf-3ee76e9404d2.png)

**Comment by chemzqm** [comment]
_shared.js 应该是是浏览器插件注入的 script, 它报错导致 js 无法正常执行。

**Comment by geeyan** [comment]
感谢回复。

诶？__core-js_shared__这个可以在仓库里搜索到：
![image](https://cloud.githubusercontent.com/assets/4083759/22302152/872ca5fe-e368-11e6-8f41-8e4b22609f7f.png)

本地链接是：
http://localhost:4000/npm/core-js/library/modules/_shared.js
```
var global = require('./_global.js')
  , SHARED = '__core-js_shared__'
  , store  = global[SHARED] || (global[SHARED] = {});
module.exports = function(key){
  return store[key] || (store[key] = {});
};
```

**Comment by chemzqm** [comment]
确认了下，是有 core-js 的这些代码，但是我无法重现报错，怀疑是你的 window 对象或者 window.math 被污染了。

**Comment by chemzqm** [comment]
@geeyan 你是否使用了 wepy 之类的工具编译代码？可能你需要在项目根目录下添加 `wept.json` 然后加入：
``` json
{
 "babel": false
}
```
service.js 里面是有引入 core-js 的部分代码，但是你的调用跑到 `modules/_shared.js` 去了，而 wept 并不会在 service 层引入 core-js 的代码，所以应该是其它工具引入的

**Comment by geeyan** [comment]
对的，使用了wepy🌝🌝🌝
加了这个配置就ok了~
