### ISSUE TITLE
wx.navigateTo回调complete没有执行

### ISSUE THREAD

**Issue by geeyan** [chemzqm/wept#82]
wept --version: 0.8.0 130400
node --version: v6.5.0
操作系统: MacOS X 10.11.6 (15G1108)
浏览器及浏览器版本: Chrome/55.0.2883.95
* 与官方工具表现不一致？**是的**

官方：
![image](https://cloud.githubusercontent.com/assets/4083759/22322369/8d061d70-e3d6-11e6-905f-1967259b7175.png)

wept：
![image](https://cloud.githubusercontent.com/assets/4083759/22322363/7c58e764-e3d6-11e6-8bf0-6b97debeb362.png)

这complete方法没有被执行。
![image](https://cloud.githubusercontent.com/assets/4083759/22322401/d3e5716e-e3d6-11e6-979b-bbbceaf8fb80.png)

**Comment by chemzqm** [comment]
是 bug，应该是我没有实现。
