### ISSUE TITLE
tabBar跳转白页

### ISSUE THREAD

**Issue by dezhenglu** [chemzqm/wept#84]
* `wept --version`: 0.8.1 130400
* `node --version`: v6.9.2
* 操作系统: windows10
* 浏览器及浏览器版本: Chrome 55.0.2883.87 m
* 与官方工具表现不一致？
tabBar 跳转的时候会出现白页,请问这是什么原因?

**Comment by chemzqm** [comment]
什么叫出现白页？请描述如何重现该问题。

**Comment by dezhenglu** [comment]
就是点tabBar的时候出现空白的页面.我把代码粘上来
app.json
{
  "pages":[
     "pages/index/index",
     "pages/login/login",  
     "pages/user/user"
  ],  
  "window":{
    "backgroundTextStyle":"light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "用户登录",
    "navigationBarTextStyle":"black"
  },
  "tabBar": {
    "list": [{
      "pagePath": "pages/index/index",
      "text": "首页"
    }, {
      "pagePath": "pages/user/user",
      "text": "用户中心"
    }]
  }
}
login.js
var app = getApp();
Page({
  data:{
    username:null,
    password:null
  },
  loginBtnClick:function(){
    app.appData.userinfo = {username:this.data.username,password:this.data.password};
    // wx.redirectTo({
    //   url: '../user/user',
    //   success: function(res){
    //     // success
    //   },
    //   fail: function() {
    //     console.log('redirectTo f')
    //   },
    //   complete: function() {
    //     // complete
    //   }
    // })
    wx.switchTab({
      url: '../user/user',
      success: function(res){
        // success
      },
      fail: function() {
        // fail
      },
      complete: function() {
        // complete
      }
    })
  },
  usernameInput:function(event){
    //console.log(event);
    this.setData({username:event.detail.value});
  },
  passwordInput:function(event){
    this.setData({password:event.detail.value});
  },
  onLoad:function(options){
    // 生命周期函数--监听页面加载
    
  },
  onReady:function(){
    // 生命周期函数--监听页面初次渲染完成
    
  },
  onShow:function(){
    // 生命周期函数--监听页面显示
    
  },
  onHide:function(){
    // 生命周期函数--监听页面隐藏
    
  },
  onUnload:function(){
    // 生命周期函数--监听页面卸载
    
  },
  onPullDownRefresh: function() {
    // 页面相关事件处理函数--监听用户下拉动作
    
  },
  onReachBottom: function() {
    // 页面上拉触底事件的处理函数
    
  },
  onShareAppMessage: function() {
    // 用户点击右上角分享
    return {
      title: 'title', // 分享标题
      desc: 'desc', // 分享描述
      path: 'path' // 分享路径
    }
  }
})
user.js
var app = getApp();
Page({
  data:{
    username:null
  },
  onLoad:function(options){
    // 生命周期函数--监听页面加载
    if(app.appData.userinfo == null){
      wx.redirectTo({
        url: '../login/login'
      })
    }else{

      this.setData({username:app.appData.userinfo.username});
      console.log(this.data.username)
      //console.log(onShow)
    }
  },
  onReady:function(){
    // 生命周期函数--监听页面初次渲染完成
    
  },
  onShow:function(){
    // 生命周期函数--监听页面显示
    
  },
  onHide:function(){
    // 生命周期函数--监听页面隐藏
    
  },
  onUnload:function(){
    // 生命周期函数--监听页面卸载
    
  },
  onPullDownRefresh: function() {
    // 页面相关事件处理函数--监听用户下拉动作
    
  },
  onReachBottom: function() {
    // 页面上拉触底事件的处理函数
    
  },
  onShareAppMessage: function() {
    // 用户点击右上角分享
    return {
      title: 'title', // 分享标题
      desc: 'desc', // 分享描述
      path: 'path' // 分享路径
    }
  }
})
还有一个index.js没写什么我就不粘了

**Comment by chemzqm** [comment]
@dezhenglu 浏览器控制没有报错吗？还是你没有添加对应 wxml 文件导致的？或者你检查下元素，这个页面是不是被隐藏了，你用官方功能也有一样问题吗？

**Comment by dezhenglu** [comment]
浏览器控制台没有报错,就有个警告bridge.js?v=0.8.1:1 WEPT 未检查安全域名，更多请参考文档：XXX
使用官方没有出现这个问题,这个问题无法再现吗?我把代码给你呢?

另外我也是才接触小程序没多久,刚看了一眼官方工具的更新日志,上面有提到
F 修复 API wx.switchTab 在某些情况下未调用 onShow 的问题,会不会是这个问题呢?

**Comment by dezhenglu** [comment]
刚才检查了下元素,确实页面display: none了,请问这是什么原因?
<iframe src="/app/pages/user/user.wxml?w=375&amp;r=2" id="view-3" name="view-3" seamless="seamless" sandbox="allow-scripts allow-same-origin allow-forms allow-modals" frameborder="0" width="100%" height="100%" style="display: none;"></iframe>

**Comment by chemzqm** [comment]
应该是 service 层 ready 时间没有正确发送到 view 层导致的，可能我把代码更新到官方最新版可以解决该问题。
最好你能把代码给我一下，我不确定这个 bug 是怎么触发的，没有办法重现。

**Comment by dezhenglu** [comment]
好的,但是刚才被退信了 chemzqm@gmail.com 这个邮件?

**Comment by chemzqm** [comment]
对，你 github 创建一个项目，我去 clone 下来也可以

**Comment by dezhenglu** [comment]
久等了,git不熟悉先学的
https://github.com/dezhenglu/xcxlogindemo.git

**Comment by chemzqm** [comment]
谢谢你的反馈。问题出在你用 redirectTo 把 tabbar 页面顶替掉了，之前设计的时候没有考虑到这种情况
