### ISSUE TITLE
用了wepy之后，wept就会提示『无法找到 app.json 文件』

### ISSUE THREAD

**Issue by terranc** [chemzqm/wept#87]
* `wept --version`: 
* `node --version`: 
* 操作系统: 
* 浏览器及浏览器版本: 
* 与官方工具表现不一致？

wepy新建一个项目后根目录没有app.json，在配置wept.json之后执行wept会提示下面的错误
`无法找到 app.json 文件，请检查`

**Comment by chemzqm** [comment]
你需要把  wept.json 放到生成后目录，然后在生成后目录下执行 wept
