### ISSUE TITLE
在wept环境下可以正常调用 playVoice方法，而小程序开发环境中报错

### ISSUE THREAD

**Issue by haihengit** [chemzqm/wept#88]
* `wept --version`: 0.8.1
* `node --version`: v4.5.0
* 操作系统: win10 64
* 浏览器及浏览器版本: chrome
* 与官方工具表现不一致？是的

## 界面截图（可选）
![_cqs w ccjz 4a nx_b7pu](https://cloud.githubusercontent.com/assets/16970657/23492452/6d945e82-ff3f-11e6-8802-d7cbc4055bfb.png)

**Comment by chemzqm** [comment]
因为为了方便调试，wept是支持相对路径 url 的，我加个warning 好了

**Comment by chemzqm** [comment]
已添加警告
