### ISSUE TITLE
firefox中可以用wept吗？

### ISSUE THREAD

**Issue by vipzrx** [chemzqm/wept#89]
感谢有这样的好工具
我刚入门web开发，之前一直是使用firefox。看到你的文档中使用的chrome，好多插件和设置都在firefox上面，想用firefox调试小工具

请问这个工具可以在firefox中使用吗？

**Comment by chemzqm** [comment]
小程序部分功能需要触摸事件支持，我不确定 firefox 上是否像 Chrome 一样可以模拟，另外 WEPT 针对 Chrome 的错误堆栈进行了 sourcemap 映射，其它浏览器暂时做不了，没有这个映射出错调试会麻烦一些。

**Comment by vipzrx** [comment]
好的，那我安装chrome学习下
