### ISSUE TITLE
chrome选择哪个版本呢？

### ISSUE THREAD

**Issue by vipzrx** [chemzqm/wept#90]
下载的时候，看到有两种版本，正式版和开发版本。 chrome的开发板是不稳定的测试版本，还是说给开发者用的版本？
1 用来开发小程序是选用稳定版本，还是开发版本？
2 chrome有32位 64位之分，之前使用软件的经验如果在64位电脑上都能安装32位的版本，和64位的版本，32位的版本会稳定一些。chrome在x64的电脑上安装，选32位还是64位？

抱歉，这个问题有些离题

**Comment by chemzqm** [comment]
都可以，开发版特定多，但是不稳定，看你自己喜好了。
64 位的机器肯定选 64 位的
