### ISSUE TITLE
Error: Cannot find module '../build/server'

### ISSUE THREAD

**Issue by vipzrx** [chemzqm/wept#91]
** wept使用的环境
{ mina } HEAD » wept --version                                   
0.9.1 140900

{ mina } HEAD » node --version                                     
v6.9.4

win7 x64

## 错误日志
npm@3.10.10 C:\Program Files\nodejs\node_modules\npm
{ soft_git }  » npm i wept -g                                         /cygdrive/d/soft/soft_git 1
C:\Users\kk\AppData\Roaming\npm\wept -> C:\Users\kk\AppData\Roaming\npm\node_modules\wept\bin\wept
C:\Users\kk\AppData\Roaming\npm
`-- wept@0.9.1
  +-- babel-core@6.24.0
  | +-- babel-code-frame@6.22.0
  | | +-- esutils@2.0.2
  | | `-- js-tokens@3.0.1
  | +-- babel-generator@6.24.0
  | | +-- detect-indent@4.0.0
  | | +-- jsesc@1.3.0
  | | `-- trim-right@1.0.1
  | +-- babel-helpers@6.23.0
  | +-- babel-messages@6.23.0
  | +-- babel-register@6.24.0
  | | +-- home-or-tmp@2.0.0
  | | +-- mkdirp@0.5.1
  | | | `-- minimist@0.0.8
  | | `-- source-map-support@0.4.12
  | +-- babel-template@6.23.0
  | +-- babel-traverse@6.23.1
  | | +-- globals@9.16.0
  | | `-- invariant@2.2.2
  | |   `-- loose-envify@1.3.1
  | +-- babel-types@6.23.0
  | | `-- to-fast-properties@1.0.2
  | +-- babylon@6.16.1
  | +-- debug@2.6.3
  | | `-- ms@0.7.2
  | +-- json5@0.5.1
  | +-- lodash@4.17.4
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.6
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | +-- path-is-absolute@1.0.1
  | +-- private@0.1.7
  | `-- slash@1.0.0
  +-- babel-preset-es2015@6.24.0
  | +-- babel-plugin-check-es2015-constants@6.22.0
  | +-- babel-plugin-transform-es2015-arrow-functions@6.22.0
  | +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0
  | +-- babel-plugin-transform-es2015-block-scoping@6.23.0
  | +-- babel-plugin-transform-es2015-classes@6.23.0
  | | +-- babel-helper-define-map@6.23.0
  | | +-- babel-helper-function-name@6.23.0
  | | +-- babel-helper-optimise-call-expression@6.23.0
  | | `-- babel-helper-replace-supers@6.23.0
  | +-- babel-plugin-transform-es2015-computed-properties@6.22.0
  | +-- babel-plugin-transform-es2015-destructuring@6.23.0
  | +-- babel-plugin-transform-es2015-duplicate-keys@6.22.0
  | +-- babel-plugin-transform-es2015-for-of@6.23.0
  | +-- babel-plugin-transform-es2015-function-name@6.22.0
  | +-- babel-plugin-transform-es2015-literals@6.22.0
  | +-- babel-plugin-transform-es2015-modules-amd@6.24.0
  | +-- babel-plugin-transform-es2015-modules-commonjs@6.24.0
  | | `-- babel-plugin-transform-strict-mode@6.22.0
  | +-- babel-plugin-transform-es2015-modules-systemjs@6.23.0
  | | `-- babel-helper-hoist-variables@6.22.0
  | +-- babel-plugin-transform-es2015-modules-umd@6.24.0
  | +-- babel-plugin-transform-es2015-object-super@6.22.0
  | +-- babel-plugin-transform-es2015-parameters@6.23.0
  | | +-- babel-helper-call-delegate@6.22.0
  | | `-- babel-helper-get-function-arity@6.22.0
  | +-- babel-plugin-transform-es2015-shorthand-properties@6.22.0
  | +-- babel-plugin-transform-es2015-spread@6.22.0
  | +-- babel-plugin-transform-es2015-sticky-regex@6.22.0
  | | `-- babel-helper-regex@6.22.0
  | +-- babel-plugin-transform-es2015-template-literals@6.22.0
  | +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0
  | +-- babel-plugin-transform-es2015-unicode-regex@6.22.0
  | | `-- regexpu-core@2.0.0
  | |   +-- regenerate@1.3.2
  | |   +-- regjsgen@0.2.0
  | |   `-- regjsparser@0.1.5
  | |     `-- jsesc@0.5.0
  | `-- babel-plugin-transform-regenerator@6.22.0
  |   `-- regenerator-transform@0.9.8
  +-- babel-runtime@6.23.0
  | +-- core-js@2.4.1
  | `-- regenerator-runtime@0.10.3
  +-- boxen@1.0.0
  | +-- ansi-align@1.1.0
  | | `-- string-width@1.0.2
  | |   +-- code-point-at@1.1.0
  | |   `-- is-fullwidth-code-point@1.0.0
  | |     `-- number-is-nan@1.0.1
  | +-- camelcase@4.0.0
  | +-- cli-boxes@1.0.0
  | +-- string-width@2.0.0
  | | `-- is-fullwidth-code-point@2.0.0
  | +-- term-size@0.1.1
  | | `-- execa@0.4.0
  | |   +-- cross-spawn-async@2.2.5
  | |   | +-- lru-cache@4.0.2
  | |   | | +-- pseudomap@1.0.2
  | |   | | `-- yallist@2.1.2
  | |   | `-- which@1.2.12
  | |   |   `-- isexe@1.1.2
  | |   +-- is-stream@1.1.0
  | |   +-- npm-run-path@1.0.0
  | |   +-- path-key@1.0.0
  | |   `-- strip-eof@1.0.0
  | `-- widest-line@1.0.0
  |   `-- string-width@1.0.2
  +-- chalk@1.1.3
  | +-- ansi-styles@2.2.1
  | +-- escape-string-regexp@1.0.5
  | +-- has-ansi@2.0.0
  | | `-- ansi-regex@2.1.1
  | +-- strip-ansi@3.0.1
  | `-- supports-color@2.0.0
  +-- chokidar@1.6.1
  | +-- anymatch@1.3.0
  | | +-- arrify@1.0.1
  | | `-- micromatch@2.3.11
  | |   +-- arr-diff@2.0.0
  | |   | `-- arr-flatten@1.0.1
  | |   +-- array-unique@0.2.1
  | |   +-- braces@1.8.5
  | |   | +-- expand-range@1.8.2
  | |   | | `-- fill-range@2.2.3
  | |   | |   +-- is-number@2.1.0
  | |   | |   +-- isobject@2.1.0
  | |   | |   +-- randomatic@1.1.6
  | |   | |   `-- repeat-string@1.6.1
  | |   | +-- preserve@0.2.0
  | |   | `-- repeat-element@1.1.2
  | |   +-- expand-brackets@0.1.5
  | |   | `-- is-posix-bracket@0.1.1
  | |   +-- extglob@0.3.2
  | |   +-- filename-regex@2.0.0
  | |   +-- kind-of@3.1.0
  | |   | `-- is-buffer@1.1.5
  | |   +-- normalize-path@2.0.1
  | |   +-- object.omit@2.0.1
  | |   | +-- for-own@0.1.5
  | |   | | `-- for-in@1.0.2
  | |   | `-- is-extendable@0.1.1
  | |   +-- parse-glob@3.0.4
  | |   | +-- glob-base@0.3.0
  | |   | `-- is-dotfile@1.0.2
  | |   `-- regex-cache@0.4.3
  | |     +-- is-equal-shallow@0.1.3
  | |     `-- is-primitive@2.0.0
  | +-- async-each@1.0.1
  | +-- glob-parent@2.0.0
  | +-- inherits@2.0.3
  | +-- is-binary-path@1.0.1
  | | `-- binary-extensions@1.8.0
  | +-- is-glob@2.0.1
  | | `-- is-extglob@1.0.0
  | `-- readdirp@2.1.0
  |   +-- graceful-fs@4.1.11
  |   +-- readable-stream@2.2.5
  |   | +-- buffer-shims@1.0.0
  |   | +-- core-util-is@1.0.2
  |   | +-- isarray@1.0.0
  |   | +-- process-nextick-args@1.0.7
  |   | +-- string_decoder@0.10.31
  |   | `-- util-deprecate@1.0.2
  |   `-- set-immediate-shim@1.0.1
  +-- commander@2.9.0
  | `-- graceful-readlink@1.0.1
  +-- concat-with-sourcemaps@1.0.4
  +-- convert-source-map@1.4.0
  +-- debounce@1.0.0
  | `-- date-now@1.0.1
  +-- et-improve@0.1.3
  +-- faye-websocket@0.11.1
  | `-- websocket-driver@0.6.5
  |   `-- websocket-extensions@0.1.1
  +-- glob@7.1.1
  | +-- fs.realpath@1.0.0
  | +-- inflight@1.0.6
  | | `-- wrappy@1.0.2
  | `-- once@1.4.0
  +-- growl@1.9.2
  +-- jsondiffpatch@0.2.4
  | `-- chalk@0.5.1
  |   +-- ansi-styles@1.1.0
  |   +-- has-ansi@0.1.0
  |   | `-- ansi-regex@0.2.1
  |   +-- strip-ansi@0.3.0
  |   `-- supports-color@0.2.0
  +-- koa@1.3.0
  | +-- accepts@1.3.3
  | | `-- negotiator@0.6.1
  | +-- co@4.6.0
  | +-- composition@2.3.0
  | | `-- any-promise@1.3.0
  | +-- content-disposition@0.5.2
  | +-- content-type@1.0.2
  | +-- cookies@0.6.2
  | | +-- depd@1.1.0
  | | `-- keygrip@1.0.1
  | +-- delegates@1.0.0
  | +-- destroy@1.0.4
  | +-- error-inject@1.0.0
  | +-- escape-html@1.0.3
  | +-- fresh@0.3.0
  | +-- http-assert@1.2.0
  | | +-- deep-equal@1.0.1
  | | `-- http-errors@1.4.0
  | |   `-- inherits@2.0.1
  | +-- http-errors@1.6.1
  | | `-- setprototypeof@1.0.3
  | +-- koa-compose@2.5.1
  | +-- koa-is-json@1.0.0
  | +-- mime-types@2.1.14
  | | `-- mime-db@1.26.0
  | +-- on-finished@2.3.0
  | | `-- ee-first@1.1.1
  | +-- only@0.0.2
  | +-- parseurl@1.3.1
  | +-- statuses@1.3.1
  | +-- type-is@1.6.14
  | | `-- media-typer@0.3.0
  | `-- vary@1.1.0
  +-- koa-compress@1.0.9
  | +-- bytes@2.4.0
  | `-- compressible@2.0.9
  +-- koa-formidable@1.0.0
  | `-- formidable@1.0.17
  +-- koa-logger@1.3.1
  | +-- bytes@1.0.0
  | +-- humanize-number@0.0.2
  | `-- passthrough-counter@1.0.0
  +-- koa-router@5.4.0
  | +-- methods@1.1.2
  | `-- path-to-regexp@1.7.0
  |   `-- isarray@0.0.1
  +-- koa-send@3.3.0
  | +-- mz@2.6.0
  | | `-- thenify-all@1.6.0
  | |   `-- thenify@3.2.1
  | `-- resolve-path@1.3.3
  |   `-- http-errors@1.5.1
  |     `-- setprototypeof@1.0.2
  +-- koa-static@2.1.0
  +-- merge@1.2.0
  +-- mkdir-p@0.0.7
  +-- node-parallel@0.1.6
  | `-- next-tick@0.1.0
  +-- node-serial@0.1.1
  +-- object-assign@4.1.1
  +-- open@0.0.5
  +-- source-map@0.5.6
  +-- throttleit@1.0.0
  +-- tunnel@0.0.4
  `-- update-notifier@1.0.3
    +-- boxen@0.6.0
    | +-- camelcase@2.1.1
    | +-- filled-array@1.1.0
    | +-- repeating@2.0.1
    | | `-- is-finite@1.0.2
    | `-- string-width@1.0.2
    +-- configstore@2.1.0
    | +-- dot-prop@3.0.0
    | | `-- is-obj@1.0.1
    | +-- os-tmpdir@1.0.2
    | +-- osenv@0.1.4
    | +-- uuid@2.0.3
    | `-- write-file-atomic@1.3.1
    |   +-- imurmurhash@0.1.4
    |   `-- slide@1.1.6
    +-- is-npm@1.0.0
    +-- latest-version@2.0.0
    | `-- package-json@2.4.0
    |   +-- got@5.7.1
    |   | +-- create-error-class@3.0.2
    |   | | `-- capture-stack-trace@1.0.0
    |   | +-- duplexer2@0.1.4
    |   | +-- is-redirect@1.0.0
    |   | +-- is-retry-allowed@1.1.0
    |   | +-- lowercase-keys@1.0.0
    |   | +-- node-status-codes@1.0.0
    |   | +-- parse-json@2.2.0
    |   | | `-- error-ex@1.3.1
    |   | |   `-- is-arrayish@0.2.1
    |   | +-- pinkie-promise@2.0.1
    |   | | `-- pinkie@2.0.4
    |   | +-- read-all-stream@3.1.0
    |   | +-- timed-out@3.1.3
    |   | +-- unzip-response@1.0.2
    |   | `-- url-parse-lax@1.0.0
    |   |   `-- prepend-http@1.0.4
    |   +-- registry-auth-token@3.1.0
    |   | `-- rc@1.1.7
    |   |   +-- deep-extend@0.4.1
    |   |   +-- ini@1.3.4
    |   |   +-- minimist@1.2.0
    |   |   `-- strip-json-comments@2.0.1
    |   `-- registry-url@3.1.0
    +-- lazy-req@1.1.0
    +-- semver-diff@2.1.0
    | `-- semver@5.3.0
    `-- xdg-basedir@2.0.0
      `-- os-homedir@1.0.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\wept\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
{ soft_git }  » cd /cygdrive/d/soft/soft_src/mina                       /cygdrive/d/soft/soft_git
{ mina } HEAD » wept                                               /cygdrive/d/soft/soft_src/mina
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\kk\AppData\Roaming\npm\node_modules\wept\bin\wept:69:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
{ mina } HEAD »

**Comment by chemzqm** [comment]
检查下
C:\Users\kk\AppData\Roaming\npm\node_modules\wept\build\server.js 文件
应该是 npm 安装时没下载成功导致，请尝试重新执行安装命令

**Comment by vipzrx** [comment]
谢谢！ 是因为使用的node官方的源，换成淘宝的源，就可以完整下载。现在已经正常使用了

**Comment by chemzqm** [comment]
就是 npm 的问题
