### ISSUE TITLE
index.wxml 404 

### ISSUE THREAD

**Issue by cytle** [chemzqm/wept#94]
* `wept --version`: 0.9.1 140900
* `node --version`: v7.3.0
* 操作系统: ubuntu 16.04
* 浏览器及浏览器版本:  57.0.2987.98
* 与官方工具表现不一致？
* wine版本: wine-1.6.2

代理关了,有次成功外,其余都报下面错误

## 错误日志

Error: fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x72e764,(nil)): stub
fixme:advapi:DeregisterEventSource (0xcafe4242) stub
fixme:ntdll:NtQueryInformationProcess (process=0xdc) Unimplemented information class: ProcessSessionInformation
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:msg:ChangeWindowMessageFilter 4a 00000001
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:iphlpapi:NotifyAddrChange (Handle 0x180e9e4, overlapped 0x180e9c4): stub
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:iphlpapi:CancelIPChangeNotify (overlapped 0x180e9c4): stub
fixme:ntdll:NtQueryInformationToken QueryInformationToken( ..., TokenElevation, ...) semi-stub
fixme:advapi:EventRegister {dc55d4d9-138d-441a-80cb-77aec617e3f7}, 0x10077e10, 0x100ded00, 0x100decf8
fixme:advapi:EventUnregister deadbeef: stub
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
err:rpc:I_RpcGetBuffer no binding
fixme:crypt:SystemFunction040 (0x1685e0, 70, 1): stub [RtlEncryptMemory]
fixme:crypt:SystemFunction041 (0x1114070, 70, 1): stub [RtlDecryptMemory]
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:process:WTSGetActiveConsoleSessionId stub
fixme:wtsapi:WTSQueryUserToken 0 0x82b268
fixme:mountmgr:harddisk_ioctl Unsupported ioctl 2d1400 (device=2d access=0 func=500 method=0)
fixme:process:WTSGetActiveConsoleSessionId stub
fixme:wtsapi:WTSQueryUserToken 0 0x82cc1c
fixme:process:WTSGetActiveConsoleSessionId stub
fixme:wtsapi:WTSQueryUserToken 0 0x82cc44
fixme:advapi:RegisterEventSourceW ((null),L"QPCore"): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000000,(nil),0x0001,0x00000000,0x72e780,(nil)): stub
fixme:advapi:DeregisterEventSource (0xcafe4242) stub

    at /usr/local/lib/node_modules/wept/build/parser.js:63:37
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  --> GET /app/pages/index/index.wxml?w=1920&r=1 404 5,736ms -

**Comment by chemzqm** [comment]
应该是 wine 运行 wcc.exe 报错，跟代理没关系。
我现在没有 ubuntu 机器，有机会我测一下吧。

**Comment by cytle** [comment]
找到问题所在,我使用64位的wine,而wcc.exe是32位的

```shell
# 创建一个32位的环境(如果有了就不需要这步
$ WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg
```

```shell
# 设置WINEPREFIX为上面刚设置环境的配置路径
export WINEPREFIX=~/.wine32 
# 启动
wept
```

参考: [https://superuser.com/questions/852098/wine-says-fixmeheapheapsetinformation-when-trying-to-run-command](https://superuser.com/questions/852098/wine-says-fixmeheapheapsetinformation-when-trying-to-run-command)

**Comment by chemzqm** [comment]
多谢，已添加至文档
