### ISSUE TITLE
wx.request没有返回结果？

### ISSUE THREAD

**Issue by bailiangcn** [chemzqm/wept#95]
* `wept --version`: 0.9.1 140900
* `node --version`: v7.4.0
* 操作系统: ubuntu 14.04
* 浏览器及浏览器版本: chrome 版本 57.0.2987.110 (64-bit)
* 与官方工具表现不一致？
关闭官方工具 开发环境不校验请求域名以及TLS版本 选项后，官方工具正常，但 wept没有返回

**Comment by chemzqm** [comment]
请使用 chrome 控制台工具查看网络选项，确认下是请求没发出去还是响应是空的。
怀疑可能是后台做了 user-agent 或者 referrer 等请求头部的限定。

**Comment by bailiangcn** [comment]
多谢，我试试

**Comment by bailiangcn** [comment]
找到问题所在，由于小程序在chrome浏览器中没有取得正确经纬度，导致结果返回无效，wept本身正常

**Comment by chemzqm** [comment]
@bailiangcn WEPT 是支持 geolocation 来返回经纬度的，Chrome 授权后应该是可以获取的
