### ISSUE TITLE
Promise is not defined

### ISSUE THREAD

**Issue by weixiao-huang** [chemzqm/wept#97]
* `wept --version`: 0.9.1 140900
* `node --version`:  v7.9.0
* 操作系统:  MacOS 10.12.4
* 浏览器及浏览器版本:  Chome Version 58.0.3029.81 (64-bit)
* 与官方工具表现不一致？

## 细节描述
在微信小程序根目录中我新建了一个tools.js，在其中我定义了一个处理异步的promise相关的函数如下：
``` javascript
export const promiseHandle = (func, options) => {
  options = options || {}
  return new Promise((resolve, reject) => {
    if (typeof func !== 'function') reject();
    options.success = resolve;
    options.fail = reject;
    func(options);
  })
}
```
之后当我使用这个函数的时候，浏览器就会跳出`Promise is not defined`的错误，如下图所示。求帮忙看看是什么问题。在微信web开发者工具中没有出现这个问题

## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/8834733/25646741/d1983258-2fed-11e7-9aa2-7b94db2b7b15.png)

**Comment by xifengzhu** [comment]
+1

**Comment by chemzqm** [comment]
小程序之前部分 android 不支持原生 Promise， 所以开发工具也禁用了原生 Promise， 估计是新版又给加回来了，WEPT 需要升级与官方保持一致。

**Comment by yangyingjie** [comment]
这个bug很好解决吧,什么时候搞定啊,亲
