### ISSUE TITLE
Linux环境部署wept问题

### ISSUE THREAD

**Issue by linsage** [chemzqm/wept#98]
* `wept --version`: 0.9.1 140900
* 操作系统: ubuntu 14.04.1 （32位）

## 情况
- Ubuntu 32位
- wine 已安装
- npm 已安装
- wept 已安装

```
wept -p 4000 启动以下错误
```

## 错误日志
Error: Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window

    at /usr/local/node-v6.10.2-linux-x86/lib/node_modules/wept/build/parser.js:63:37
    at ChildProcess.exithandler (child_process.js:195:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  --> GET /app/pages/index/index.wxml?w=375&r=2 404 4,707ms -

## 界面截图（可选）
![image](https://cloud.githubusercontent.com/assets/12984934/25788934/68b781bc-33df-11e7-853a-a065c253a753.png)

![image](https://cloud.githubusercontent.com/assets/12984934/25788944/766a249a-33df-11e7-8dca-c8e206d43c81.png)

**Comment by linsage** [comment]
wine环境问题
安装 xvfb  模拟娴 virtual display
sudo apt-get install Xvfb 
参考：https://superuser.com/questions/902175/run-wine-totally-headless

**Comment by linsage** [comment]
但是启动运行一会又重新报，貌似会变化

**Comment by chemzqm** [comment]
感谢你的反馈。
wine 这个东西比较复杂，建议还是使用  Mac 或者 windows 进行小程序开发
