### ISSUE TITLE
是否可以兼容一下wepy框架，目前好像不兼容

### ISSUE THREAD

**Issue by baijunjie** [chemzqm/wept#99]
* `wept --version`: v0.9.1 140900
* `node --version`: v7.4.0
* 操作系统: mac
* 浏览器及浏览器版本: chrome

由于 wepy 在运行编译后的小程序文件时，要求关闭微信官方调试工具中的 E6转E5功能，否则项目运行会报错。
因此，wept 运行 wepy 编译出来的项目时同样遇到了这个问题

是否考虑可以兼容一下呢？

## 界面截图（可选）
![2650af1d-5068-4fed-b497-38cb82d2902b](https://cloud.githubusercontent.com/assets/7956480/26026493/ba66a45e-382e-11e7-9989-2a784a4d2058.png)

**Comment by chemzqm** [comment]
需要配置 wept.json 禁用 es6 编译，文档有说明 https://chemzqm.github.io/wept/#/home?id=wept-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
